apiVersion: ENC[AES256_GCM,data:tTk=,iv:p2eVwflQbQtQCPRsUeG9M23L2cwoUBv0mylu+tcWvsI=,tag:lJN2xqTgioVYtsjfBOG3EQ==,type:str]
kind: ENC[AES256_GCM,data:fJqwIc9S,iv:F55Epz0/QSEncMgjnZzCkRN1zecEx+QBgYQsTzU3Jwk=,tag:Uk9A4PCYqxA8TeTk1oUm+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QHBbuDdvXia0oFMwsn1Z3a8XW0ki3ycP,iv:HWzLOcND3jupbbbobfV/pjI6XLf7mNcAqE5S65ceoDk=,tag:DQS2ERHpwK1lbIBH1HHKEQ==,type:str]
    namespace: ENC[AES256_GCM,data:AnLRlA==,iv:FaLANme4IsP2ZxCYVzmveDT+cSBxSVDQuv+UY1kBd9U=,tag:PeB9REv3uXLFo0M18VY6nA==,type:str]
type: ENC[AES256_GCM,data:IwVd3i1f,iv:6K25ED05akdOsHmbRp13b/T/hqi0DfA8T3DCgCPADWU=,tag:lwf005BCTKDIlBDwn9v+NA==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:KwdfyE0IwLnZBZ2qEXmR5GUMpjB4klbrz3VLZXVXSmOTVsnG0IpaOCtAd/0ksquno3GqFT4iSJHlVLc7LZ6lspjZMbedHobDpYKIYUbT9ShV7W5/qvAI9JwXPUNsBicgHgYaHNQzNKkq7cF9Et8=,iv:RzK0X9rTvc6D9QGObaPCy6PIWX1DthvntKgV9Chm9Xc=,tag:FNld37Zdad8E6RcTZcIwpQ==,type:str]
    PORT: ENC[AES256_GCM,data:/alePw==,iv:RvrlbsjwFNitlPNzNRW5ZRvI+WreHJEUAPIFAdtKeew=,tag:5UkKH6MpXhpYpIAyu50fBQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:koVOdZ4b6Zi+ZRp34bU=,iv:goYdmCw8kmRaTSHQg6HSDQM5IyYmC0ifl6KC+yO/YaY=,tag:/AbN9AjL7H4OKpNOWdYnRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraGNrSWdWRE1yOGx2Unc3
            TU95NjFmdkRjUkN6SzRNUTVRb0VNRkU1M1dzCkl5VmsycjZvRjRWeW5Cb3dhcjUy
            L2phRWMzN29YMExjT1JCbnREcVVJSkkKLS0tIG1oak1TVmNTL2lkNml0cytyREo2
            aVVGZlpBM3pQSWhraVFGTjNKVGFpTjQKajZv6oEuST2g8waETrnmmilMnIU4vRlb
            SfMKBm/WlWyB8y1+zjxvY6pVyh2kxKiTbylfTZycKfUduH0L2LTrYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:51Z"
    mac: ENC[AES256_GCM,data:wa6xhDO2viAuWumCRZ4YUJdPBSykhs9dsG1Z3eFlj/ZJFf270WQBCAFLnNceFynAXhLPe3w+E4gjLB5aZl6Y9GHy7qSOs8UMdDRCzCVw3x94ZpuNzTrEfSkbQAtf3+CVNDkQfYLl1dnccn3Qkme/+A/0+beVo3aQR00VGPK9tvU=,iv:aUxNiYZkxobgrC4UuIIbMThNZlGKZRhiYWGOqm27lPw=,tag:InBW8ArK8ilXqm8tGE8DiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
