apiVersion: ENC[AES256_GCM,data:9bg=,iv:7n4A9T8h2wBcb508UK1/o66laEOgVe0aQWDMnmE0E1o=,tag:+yz/xrsKHuCOrErB/IuA2w==,type:str]
kind: ENC[AES256_GCM,data:bohd1gAG,iv:txjKrjAmv//bZXNlRDuBFs33kwKm8l4SsCAcKDiaD90=,tag:VwI2BUaM//BNuik/tCOd3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4OW4qnFOJ3PxQdFcutRrsvyAlXlpIb/H,iv:b/y8eUVl/jzM8Km3q5epgU3T0lCdgbYUf6DCOt7RrXA=,tag:DioY+GFIxaWpViHy1vJWvA==,type:str]
    namespace: ENC[AES256_GCM,data:cgG74w==,iv:UErGyMoHJQafjhKidOhFDAdTjbwiLOGDXfBEUjpq8C8=,tag:LhwwX5ttNrbghQstRTXtmw==,type:str]
type: ENC[AES256_GCM,data:vNq2dAWS,iv:fTZ0m9M/Zw138helx/VwaT4v3yy+tXLiFsY8PdaZhxs=,tag:N1Ffi/6LFGl43t9IEV/aEw==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:/eC9HznZdSD90jTMOOAp+6vyl0Tvku5DG/wHPQkrjnKtcex/UoCjzIHr+XoVzzZSRVgJf7JV/Zt67BT+LAIse5is4LBHx5boce43rMX5Bbjd1IHlRZ4vbE6Rfddz2HGBZLUw8lau5q5zNHodPbc=,iv:ldVMQeGx2lhPZeUSUzvygxnPN+dcBo9z+UElU5BmG74=,tag:7JxCeJc4QrN8y08w1NQ8IQ==,type:str]
    PORT: ENC[AES256_GCM,data:wKO6/A==,iv:1MPs2W5yGhixFV1Smx3LBilux3H8J+Jz+XoEb31YEYg=,tag:O12jn/cUFAJDh5IRxKVeLQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:UXE+xymjjzb3o9Eb9zM=,iv:lj26ArPnhirXfrQmhK2LLseAKmyHGYTjazc5LKPZ1Wo=,tag:h22/5G8iTEZ5U3Dl+2hLQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZlFSbVd0eXd6d0ZOU0Qr
            NTByS1FyZnVkbWdjWXhQeHhieXZrM2x0dENjCndUeGxxcGlVZ1NRUDF5UW5CWW1u
            Uy8rc2c3YjZoMmwxSEFQS2l5cWRxWXMKLS0tICtKMDZHNWhoQjBjZEZRakUxUitz
            U0hYTXd4S1lwMGR5SGhXeFJpNmtqVncK1qQlt0SYRhSyxgJXRQ+bTuQLeXHC9+NA
            59jy0Yl7lmEF0NWnZbU+1XpiKKl35KjQX4bJJ7aksinjQS1t/LlwkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:49Z"
    mac: ENC[AES256_GCM,data:FXPLPww3TCWC2UMK6VCfxeiQRxK93k8dqpvUy8+6RAdgB3ebOuHHv390ZV5+y+Te7546t6rccA2ap2bGHVLj0ilWRZp4BwrlCTpriRAVZULv9qSPdvvQTnxW9qfF6TH6LC9lByjQScHI9/IE3ynl8E5kvIUadAiMvInwIktHE90=,iv:MdhF2Gbk1MurNo8Ilh3uW+MC+B/2KPJvpR5TJD9bpg8=,tag:9FATRzi5+ZVOReVQx7s0Gw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
