apiVersion: ENC[AES256_GCM,data:qhs=,iv:utqQNBGIKblOgJi8TRwQ16DU+C9O8v5Ol3K8jGM14+o=,tag:KahJ8DGdcGqDHNPv5kbh4A==,type:str]
kind: ENC[AES256_GCM,data:69UBzNM4,iv:jW4Hc9cxICVy1YA9ebQQkZoHl6/MyEzQs62dqHzgXuY=,tag:cZtIO1G0RbCZkVbyXc6jEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+0fH7+b83bB5JjFE3uqjPsBzV1gJ1oCw,iv:EvWvwNZCG7vjBnugfXWutLJq2a+qWy38do5MnRw6jbE=,tag:94iN4vFzTqWFTv5Ea6K9PA==,type:str]
    namespace: ENC[AES256_GCM,data:jIetAg==,iv:kghW3FHlHrVRsvBGH4Ox0Z1yRgzKbGXbo3DRv2L5gD0=,tag:rEp+Ul+n+JtIpf+L0gvbcw==,type:str]
type: ENC[AES256_GCM,data:tVi4QgI5,iv:/bYCSFPloKPCKOCJwzvUk+v92zq3mH0bEefDz/8bOQ8=,tag:Fkn036RJci+K4qfvuY1CnA==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:PbdK5jLXY3mNrmqY0ZTkx8dcodjODaXyJqVHwVfIIC2SQw0ahY6C3/0L7ZYPQ1d66NulWO+ZpjioeV3fyBZ0tyuzt3jGL061A2aDEajyIu5+k3jmM4tC5duM0T6oybXyJVjSORnC1NZdFq8ciJE=,iv:ShFWiG2KRRnSCmiyrGiZ16JWahlLOhRrPtmTtoiMNU0=,tag:VGZsGzAuNQI896C3teQVNA==,type:str]
    PORT: ENC[AES256_GCM,data:MPg70w==,iv:OEO8/oebqUaJ1dtDGQ6UlUVb2yTJEeWTRFkhGsdBemM=,tag:czClC1sIg/4JLfVJ2j6+Ig==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:V2UdhnexzXNPVmCPZQA=,iv:MQ14s1q7xINeFHSX8l2CyXKK+HY2/BdhGBs9G8bEEO0=,tag:ThGqgYxbKTCiOtPCHiu4zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NkwwVTcrY3JJOXh2ZVNi
            UGU1R0FhWVljbWp1TDF1Q1dqY1ZkdWUzY1NZCkNwcWQwcXZaSHN0UFhxamkrNys1
            NjFWdGtsblJJcVdnMkFJMWxUZFhYY00KLS0tIG9ndVpsRGhzaW1NaVducXJGeERD
            akV0TXhvVDRBV3ZkTHBhV3lucWpQWTQK4jo+nyUbYRwrS2qYCl7wSBvHXSwl7RSz
            RYiM+T4y/fYyN3GFEZUlmHVzYUK0CPPi4P2BmkIF60lAmbW7NLHKrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:46Z"
    mac: ENC[AES256_GCM,data:X8r3+bAWKsvxTQSiJY5M4ANzRltf5i39oACfNBiTjvh4vSBAgUErxrVJPRxjvVt7NPA88UEYKo02aCatdXlOdCMRmpdSe3FaZaXgVvNofpYgHoW0rY7s+o6l/YGjh6c0YxyM9T9jXE19ST+5WK1CBCvJx5atf9X4KidXNjXtUhk=,iv:vSuj2hVNQ8hmq22StZvurnlSojTbe9FF0bpSVoyfYFQ=,tag:XbtpfNcQqLObJjUgxGLL8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
