apiVersion: ENC[AES256_GCM,data:5HE=,iv:OqgXlAGDdv4DRWyxVUU2xNpQHHRQCivGxXT43RKEh2I=,tag:0KOObl6ql1HVnUEGpjmifA==,type:str]
kind: ENC[AES256_GCM,data:coLvSXVd,iv:HC04HkiZVdTPUzkA7Qj973ixfjA6KnYQKzvamcbyzTE=,tag:qtfBm09jw8ih0jEOwFfutQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+TF/wqtCcsngFSyUA5rV9ppG8v1jgg==,iv:JtP4FYL/+0EeGIB65WHs5PRRtTvexrAZP/Qq+OTW7Mk=,tag:gEthuDbKFgF8c029oEnddg==,type:str]
    namespace: ENC[AES256_GCM,data:pupw0Q==,iv:wKNf0C7y6ItTUFiFvIn81GLSqU+Nr1/+1ZqGrwWx/oo=,tag:JAkho68ELa6juuAd/7QjeA==,type:str]
type: ENC[AES256_GCM,data:TwLN/+XR,iv:+rIV2UQrDbza9BT4VPMyAKW68K3kj7OwpzyuHEvGPJw=,tag:oCx7qyMXPNNq9VQ0F8O2fA==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:c/qA6VLU+sopY8T8ONBktQazrY+uthPOfu0vwOFrmhtWeR6wEHNNtpKmrAMUKDU3bBsNknJ8TTGRoM2bZLKlFGFQp8OGW87/Ki2ghR+eOzWwi3XdarPb+AIzNPlasLm24qT9SgH/KFAFlFCZTgmv9K5s8UvghNP7,iv:bUEv9jxtlJ0aos6H26tb8pfELOIoD5lEeif3jOJ+dP8=,tag:n0V5SIGo4cp+nyuM405m7w==,type:str]
    PORT: ENC[AES256_GCM,data:S595+A==,iv:9ojQB+IfKFzfhAXG7XwKHRsfjB9UxSsExeLfIxeTDWI=,tag:eSbpac88EsUeRvO4iXSdTA==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:k0Uo6ld0lhI7D59mj/rhci6/s8G5sGkulhrm+CBRWVZdO5QL+IF6zn/7/lPc/tDyiC9wKJCiyqWBipnvY3wJJ3qaSHsD,iv:Xv3apSx7GI+ESkLciUX/8pNcrU/TctB1Jm8/3kzUJqk=,tag:dASA1KDOsoxTM654l3OXtw==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:ohnwGeJ6p6PsWr4j8PdZcIMaRv6Q+aA87w==,iv:1E1RC2WBQIsvHl7YUmO7AKDAdSWCZV1Ba6elPcmIbjw=,tag:q92Ejmg5IfMjW48Ru88iFA==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:AMZJO6Ju0DRHyewwZ4BYJho=,iv:sZJLu5R0VOgYiX8EUEn+BFDwLHZk38w5eDCfqJknAz8=,tag:xZ6uYa5/31yxrmwNnCLu6w==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:6yyh,iv:YCKsAiV58g5fIpNwmw/AjeB7ZAKaBWgFgJhhRvQKJoA=,tag:wDbVQlKRrCU91YeUVzqFKA==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:w4NlaGdX,iv:tSbujuffhToq13hbABG94xFI/RVxvXpxg8K7TXlatAU=,tag:rVGyBAE8pK8bnG84Ijm62A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVzRsWXBLb2t1U0xGNmJo
            SUUwNDlEMU56cGs1NTdDS1BmMkFDUE9YRFhFCjEzM1o4YWhzL1ZZQldaSy9vYXo3
            akRKNkYxeXFqcGdlam5UK3hwb1A3Ym8KLS0tIC91SnJFUlEva0k1QVNoU2QwT2tS
            cGx2WGZuYWZOcHRDbkVaMHJCUS9mWTAKhF1slN8E30sEQZzpup0P9t/GcCzhFL66
            kWCGtjzaxp2aC8w+RhKqlznhlsDb2iHHkrXJ7c1KpApnI8PRXIqaQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:50Z"
    mac: ENC[AES256_GCM,data:Kc0aYyNsEjIRSMBgOB9hERGDV2pgZCcB00wxWxhP7PUY+dM9bbCKuK53UrpN/yDB1KuJHPIaTlqG12gvxJMZv6p7+a/wdNh97w7H4SWnNVI1B+bN/xuqOelBqfu5VD5U7IVogZi0sx4v+khX4Pe8KzoWiwXg7uvHeLNCoDXkmno=,iv:6PqR6gdlAwP8Y1CEYteMgAfKbZFIF52f4HNQLmmsrY0=,tag:ESqYzTl50mvY7SkyTDZwvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
