apiVersion: ENC[AES256_GCM,data:lAA=,iv:CHyDmrq0hlEduUBshHG5LVB7SrEOPd7/id6SDOqOAlo=,tag:SWTnY8fGyMCxwXodSxL6lw==,type:str]
kind: ENC[AES256_GCM,data:o555XySI,iv:zafK2KRsX1FtfgT+lh3Yv6u8VGHoL5h/SBTYGsZq16A=,tag:Ho+t0FdqYc4grpS8QkAMlw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aNw8RA9fp+0RQxGZgXq30e3DRKHjag==,iv:uBOwF8TWmN3W3UAdqsB/do6TamWDz2y7JOcBhmqM7xk=,tag:5V0lyfbb4tBiETSbQGHutQ==,type:str]
    namespace: ENC[AES256_GCM,data:mPjA,iv:kAwzJCBywUJg3CYcIOvQSB48RNX1SpzH9uvHZyCVHRQ=,tag:4BCQMi7Q9LqiBUWruP4EuQ==,type:str]
type: ENC[AES256_GCM,data:NV6a7lrn,iv:KzCtQaF7WZIo8Va8kjGnEkAFqs8cSbum5sLK1PObgp8=,tag:Nsj5Y5XMGm0gDP0nN6ij3g==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:mY40+YM107VOW+a8pxid98rkp60x7gOiPPcNmrgz8xzgLU9YtkpG/h5fxtzY/RckzxmUSFo0YXWynvXwib36taOgUsA5OVND5g28eBMKo0FHWGARMrx+EhehbKa2OdvT/ftaTeDvfBdB8DHucjGzD3VW2EBIw3Ak,iv:lQb3u8QnXKxR44qV5UUvjtaRXHktJ9ORqZq5Dnk7a5M=,tag:LX6BKxkKCkBpNl+H/UWOZA==,type:str]
    PORT: ENC[AES256_GCM,data:+CaRTA==,iv:x19aZ/mJvkh2hM0VmsmEoW6T3VJYJ93Pf3t/Mxaw92M=,tag:DBUz4sMunijapDwnjqZqwQ==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:so0m183OPzoSn/X/6PSImkBX/kVOc/ro45pCWmZqIUFNVqD4XXwzqoxNznK2tVZJtPXq0PsIWkWBgaymU2v339u6dcVb,iv:HrRvsLIoqp9sQN9kIBOOomnay2PwlRkOb7lPGEcv/+I=,tag:icTFq/uDBo06ZE/0u0R5gQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:M/gMPOA2TB3qzGIeSyS5/mnJ3wRPVcZcUw==,iv:l1yVOTMupHbnT0oP56H7hgtLMjO6WaNL35wOnFF2Yis=,tag:yK0W6mP8bpfqbzUqY1Uzzw==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:NtAYK4mjkCPVt8JXGvnAu84=,iv:c9rRGWl5CmYpqsMoq41Xyx6h5Rkc7qTREVe2raQMPkA=,tag:LpA84Ch82fwoIxWH5Wy90w==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:bcat,iv:dXCpjTwLmQt1dIKcUv7jfu/Gb58dYrTSLQMpWii+Cmw=,tag:ZMZzHbTz5XVSpW1e+0dHwA==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:rRHi2n54,iv:GZ0i6qC/vFvwGTcOFMZfGM+iqMvX2mrqekIxsdBsCgs=,tag:ZxULDbSafcK0EtGOceRipg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwK0FPWUlQT0dZRDZDYTY2
            U1VUSzh1QlhpTWV4WlF0TlNtRWtuVFZPZFNZClhRVHFPUjAvYzRDQUpGbDBVWU0y
            a096ZU15cnp4UWFsSGFxeFZma0hCUFkKLS0tIEpRbkt6OUpOS0F6RE13b0NnQlIv
            NEVHVUFXWm9vOUprY1VPbXM5a2xzUzQKkE+BLaFL5g/CivdyfXGEMS4xhvtm1w6b
            QFbAjC/u04Vpw1pJhKtUcdds5zhRV2h+Vf5UJuDt+uudJ9QAdU4mMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T17:59:17Z"
    mac: ENC[AES256_GCM,data:whHttHeU5272I3x6puhgUbpE/ozofxdo4bu32ulPik8v8N7XFAm/7ml+e1PW+iFi2VRtLXrL7YNBzVl1J72aOqeuRt6ZRygC1BkRb1Db5knExIuY8zb5XEHF0T5IiTt9dDyR+iLo3z5HkBYsDTRwvFRSm6337waiywaoNpApUSk=,iv:oK1M3G5Ro+o/Zhh1j8ZzOet2zhdN1D5fCY2wz/Xtt1E=,tag:QnDV94Dx8cruDPPEbBne0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
