apiVersion: ENC[AES256_GCM,data:xiU=,iv:enWEYYDN2O+spPiXLwZMxR/fvlqS2ATlPR8kHESv/Gw=,tag:t/PFlZs5uv5XB+aTrnaOXQ==,type:str]
kind: ENC[AES256_GCM,data:E+2s5FNG,iv:9ykzNCOphumo7Hbl3t5w2vBT3foB/jO2OVzKaqyQGKE=,tag:6sNJrNWNiqF+iOfCRttaLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AZ3KoT/3yDdxGu2lJ0H2wGbcw5OAnw==,iv:3rZlQF0drobpabM73/44jbEOoNZ3FXUcrkzuv40nQD4=,tag:pvgij1Wk1ZtftRU6MNZWiQ==,type:str]
    namespace: ENC[AES256_GCM,data:ooSs5g==,iv:vbdB/YP1FBMZYcwLkY9vIIRVGdI6ipgVHRDNJoKC/3w=,tag:SviLFc03PTE5fLPg3Ldjhg==,type:str]
type: ENC[AES256_GCM,data:26Pc0TQX,iv:zNbzPGcj4usIS+wz18hEEpa5iZAZCFd6/kQ5VOJm/r8=,tag:Hu/Hh8e9ZBH5qJmgi9tyyg==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:0trC77VX5rg20YlwZMwAxAg8kC0yzjjFoj4pPipeBwLvi67Jkz9ITHr7TDUA9wHngDtlMb5g6MijpRhzpgIqQs38VB49t+ja8tG2cPbOOtGLiA5c23BugsXDYE+lGhfFLfXcI6U0NUckdpNt4HKqiS6qS7q3Qia0,iv:QQQh13ilaZTONO5P8xEOX3jugskp8Py6sAhzS00xkTQ=,tag:mukHDz4v4r6TXF05swO5ZA==,type:str]
    PORT: ENC[AES256_GCM,data:EWhM8Q==,iv:8t5QJoxXF93evdu+/tt/3W24rUFTLh36inWLWxoobug=,tag:9TKfQNy1Glwihq+C41Uhgw==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:EkmlIovbBQ/wZkvMC+24DdMr8/CXa6iXVf1YnecpGUtp4fiAKSjkunzz5feTKoOeMof2LFu6EF2SXcZhzv/KLSid07OP,iv:cRdVQEZkgHP+hEfmMQONSZ0vJ46KTHugR3wYfYjJEkw=,tag:wAGFH/GnpjNA/SOVwxw5DQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:lZ8ohcegEUHCfUi49leiNDdBvOQozVx6UQ==,iv:yLhBSTuA7aJRccKryIva0NLpmscuU3yZE+ce7BnZncQ=,tag:FuzhvlzsCUwbHQse4jQjIQ==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:fsPsXNAdxRtB4tv7P4HWyFc=,iv:joXXqVPUzGaL0zyQVQitbjCuVhNC9R1MS7AME3srcPQ=,tag:tqGF/ZBWnwnWfYpPRmqn3A==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:eiXS,iv:LtxAnD9ru/q5bqPxEJgOXs3jljveHrCmQpJRTi5/Bfo=,tag:9BWJ856lHALKwARmA7vCJA==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:8tgebOCN,iv:qlWd2Dp5hmrCjNfG76iZTbkslU0jBCcP8Qre7boGb4I=,tag:cC2zIi7WO+/nZXq/O9CC/A==,type:str]
    API_URL_AUTH: ENC[AES256_GCM,data:KD5wUgj9Ire/IGCgI3ljE6fJVutCmb7NwA==,iv:kGkhgvXKfscia/yH+F9TpgtwGrE0zk2KiC2ypVfLpiA=,tag:0vFk8hYCKWdS6nnrqdwMkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOThBY3M3NWNkei9JM1A0
            azVNTVFUbGd2Zk9Id25DMkZNQWQzVUo3NFc4CnVLS1oyY21qVWpreXRFbHd4RFdp
            ekZNQ3M1NkxTaGsydmRGZXFGM3l0SHMKLS0tIGUzOHlNdk8rdjgwVzVGcGlaaEZ3
            bHg1NGI0ZUNGWndnSEZ3R0JKVmZNTmsKL9OIrvqKdmEPbz6HFnkEO1ZLxUcOTATx
            H4x73i8gHgJECgiLdYQjId8X7ZhiMu0TRjlxs3EI69b+av0hi/ygFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:53Z"
    mac: ENC[AES256_GCM,data:iNdGnvrnuLnw5oJ4fh3CJ25IEvLaUi2y9I1VE5RaNbGba22U/gPaDiWDgY/1AnxrONrTRwJ+budnA4crliDNgJ4MWH7rP7GO6zdAauNzxgeJCtl0nYA2zpwd1PBkraQI74G+01sqaXYYUtWQt5Wfr+FdNpea6z4G/3PSqbGIbNw=,iv:LYuXnD+1v3MOKyzhQYQr/+gOlMIRKqB7RiQiOcyDpQo=,tag:ZOz/jrdTktV7WwhSVQnwkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
