apiVersion: ENC[AES256_GCM,data:3e4=,iv:W2Go7jhZ+B4TtVOSNoC6uYMSwCwY2YKNQhvxUS4hHtA=,tag:ILCwBC95gYQwjafHJnMWIw==,type:str]
kind: ENC[AES256_GCM,data:jzhKpt6d,iv:vshcxnJVDjqr8Z8n1WiDKF8g+VoSlj6XkHObo1VFdj0=,tag:+vkwlhTymX1k7MJy26LgPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+BKdlXETIXxBjcijCcyk2fk=,iv:8DrGnZfs5iBDml7nIv5qzB2DmQVi/5GnUMLBHZa6jPo=,tag:ZaJ/T+NmT5Y7POTdr6pirg==,type:str]
    namespace: ENC[AES256_GCM,data:p7kRbQ==,iv:upWmS1uHzBZhJ1lmQ1V1dPgdXmGrdBwBJj63/YFlmiI=,tag:6Y9CXYq+F2I8VgmAgzMr3Q==,type:str]
type: ENC[AES256_GCM,data:4U9RdviV,iv:Rb1VY8ubzu9YvNI14UxuOefmrBqQqB31K82b9W15yxE=,tag:NVyznuikojpCkFEAfFcYHw==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:V14NBFLCBL8tNCGWaAh67AeMeqSGFWb8pQ==,iv:kIbHidR1AGWFMEtWGrFDNGWDDD3OOJ6Hsnr6ieTqcZU=,tag:fuwHNA6+dWNTJJ6PenJ6ag==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:t8+/hxtdgTMjAg0+6/77gHhYng0ITtGWJQ==,iv:ZWzgwkq8qaJyDf1rT4ZmMmz2ZzSGb+eUIencbp24RhA=,tag:R3W3XVOU5qwYFdXEFU9wXQ==,type:str]
    NEXT_PUBLIC_API_URL_AUTH: ENC[AES256_GCM,data:FCkktZ9Ytu0T8skB3EcXCik5ketocUtEcw==,iv:VwUu16wSShdjdsNfub+DYyl4HSAmQ0U2Eg+2+ksr2gQ=,tag:cXx+bqV2saHpqjEcc8jNxw==,type:str]
    NEXT_PUBLIC_API_URL_DEVIS: ENC[AES256_GCM,data:JR033GKQX9HXO7x8CNbnYE+//ytaSJcCNQ==,iv:/YhEbzMqCYeG4IPgVCEY3KHOMlvc96IbQhglMUfb194=,tag:RX1mzB4EEkX6TDPh7eNTeQ==,type:str]
    NEXT_PUBLIC_API_URL_JOB: ENC[AES256_GCM,data:0n4pr5fzSm0Hp4+FzS29WV71XJ9e8MCGYg==,iv:xZF3QC+5A2N2qKGBU52id8L/LGQHP4YB2r4Nq6R74WM=,tag:s1EXXKcR2sHR2Dpud4VMXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTHNCZFVad2poNkdBSHJ0
            LzRwQ2VhaG1tSUhlSXFwTnVIclg2aXc3cEJrCjNqUUx4bitDOG9tU3RTMjFVM0x3
            Z2ZOTGQ1aTNRRmZUeGhNc0JhNHR4eEUKLS0tIHl4VVlLMnJ6MUhibEEzNHhmeTlj
            U1pZVWJpNWhDMVhBOVJhbmJzekZwTHcKE3ZL6zeZTx4ngfsIzCLN0H/Xk5XqelP4
            mdChhABA6qhb1h1T3QDT4ekeMx+i3U2xKd59Ko2D9kvzKagoHDrSXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:48Z"
    mac: ENC[AES256_GCM,data:z+yI3z6lRhmz0oZlf3gjJJZ72NNWIPPTJ4axe8HTqBXzzdf95Y2ECSXemC6yzDRBfc66X1TIcRnqBs485CODya4RgudMlCpVq57kgnm6e3eV/7NCMXIRH4fpT18NshGEYzqyD3gRoPaBGWORhqD7TJ9vi+ZxEq//l6P5Wf4cqXA=,iv:TMl7m3aArBulZVOePcgcfvD35xCECxPwS/5LGnKDufU=,tag:xXkJNQV8HKLwKS2XFgmP6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
