apiVersion: ENC[AES256_GCM,data:GFI=,iv:Nk7NW+6SpdcVR2kIA/9w0HNgndOmW1XHvhqewJHchOI=,tag:s9yk1Qo2pec9NOWseOIRyQ==,type:str]
kind: ENC[AES256_GCM,data:fgDHFHwM,iv:4hl5J69orxXreePmM7t16yywdnz92bx1oqABGlcWXFA=,tag:ipVYl68JJTGMe9uwaIp4iQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PnRkeYF3puoaFzP711y1W+s=,iv:auY1AjLQuNqCQNGYmlTIfINfYFF0Cit25tUW6AlvJi4=,tag:DpLWybbU2MqZGXsyv6jHKg==,type:str]
    namespace: ENC[AES256_GCM,data:4biiKw==,iv:XethBdR/jeJ0Jrd3Zxtat3intX7teODHjqEeNhbczE4=,tag:a6MBGNQx1mSC3tOCZaC9AQ==,type:str]
type: ENC[AES256_GCM,data:vxuRWx9a,iv:SIuq5bd7ytB816IAIIuloDO/m/R0dYJSRQ2Ld1zls0w=,tag:TybV6A22PwVfrIQAtENeZg==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:l3ijBiRNZtBBcIROgqJsLHQSIYZTZA2WcQ==,iv:o958hVn7P3cQLeo4LV4BwswYsVgQkW6iBIvmY0brU+M=,tag:qgN4aCGfcrk8LufarmppBg==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:A29I5EmqIoXs3dNBk7iCfi+YQaIsQrkgQA==,iv:4zJkfrO0OgtdqlYiOJNmNwKTISXJ4SLtwPLPCYHsPw8=,tag:W00+yE7koJJey60Vrvi2eQ==,type:str]
    API_URL_AUTH: ENC[AES256_GCM,data:6pvHn8hSgjSWzuUkSNq5s99wb2obdz3JYQ==,iv:xEJ/tlW0Wt5iZ+8Xd+xvA8D0tnSsQob6Atj11b5SR7o=,tag:kJPHGRa4VaITW1PZLqq+OA==,type:str]
    API_URL_DEVIS: ENC[AES256_GCM,data:WwjjfFV2jyKkvCwFcYhB4fzT7dlbPwp5cQ==,iv:50/HbtRTg3n5hmmGHOsP6Yh7QsuPQ+JGBWmS7+WXrIQ=,tag:5fwTxHXEEZLTj43mkgq6gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY2NiRWR6dTJpZlY4TklC
            K0RnSHIwT003SDV4UFFHRGZRakgzU0JmWXdNCkR4Q0tEYlV1ZDVwZ0REWHE2TExW
            b1JPRnhWbUtZYnl0VisxY080aDZmcmMKLS0tIG93SXRXYndDMVptYVR5UXRSUXNC
            NWg4MW02amRNWVo2ckdhNko2eVBsMU0KEcrsIjp88kUen8AqA6+iR6svX+qOEZuI
            qeRpu2lzBz/yJilWYwKq7CM6gjI2ggkuuToXaAjF3RUKGdoLq3R2XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:06Z"
    mac: ENC[AES256_GCM,data:zKGRcYD5dlXzfV5ULI9ogFfX5zTG+MnfwmdgMh39dNp9mSLR+yrJRiQHZJ9Su3K8g/1JWUEk7psVI368k2JyA9B6BBOIMS7i7H3D9MGVKwYNMJfJFnNsLKurU+xUbZMlm6kiiTnwjXboTUQtKw9KDsV9lsrdsF4fa85GHjBcSHU=,iv:ONslUOrdknNX/bpOK2eBVg3qvPOONHo2BRINGZvBxiE=,tag:lvveOfBolGP02q4839fmkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
