apiVersion: ENC[AES256_GCM,data:Jsc=,iv:WXM4HnYOGSYM0wrkkgExefiyJ8mKU4vUqA8pGQy4x0g=,tag:Z4elyjC1rE8DHs0ckl7ExA==,type:str]
kind: ENC[AES256_GCM,data:shbqGU3d,iv:l2eAsbUdOgxDa3llZKZJEflSigqf1LV/wsqP3j9WlRI=,tag:i89OyYb9NaWDCYC10MOs+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZU0xcuQW9MYFVU3oQekJOCs=,iv:yR4/K41JMEHfoaOlgNvWNGhaFUln6USesmtAhqW1Fnw=,tag:FT41irEawL1ssbPCFTkA1g==,type:str]
    namespace: ENC[AES256_GCM,data:XU/rIQ==,iv:9qYZOyiGaSmHQfpki7N9gA/Es1DYon8O+ZVZccIBx58=,tag:F1A47bJQTdm6R1Z2i2yiww==,type:str]
type: ENC[AES256_GCM,data:7TfpWpqY,iv:jR3cVu5JyWWxY2Eb2yTEZ6tlnGJdkzKPlBrcztgIAFU=,tag:31oLsB5V8k9rvArAups7zA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:571p6Beo9xj4UemaKfbA0d5WJrbota6j2g==,iv:CrdxH53/Yxs6QsHVZEGM0maaFpF9qg/r7bYZFHmxkFI=,tag:9TYwFnwP1sAbWWUVnwvNMQ==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:RnQgSS2jWNAwjfPbvmp1P7UvRiL1fJMgnA==,iv:ueYZJTiYuEVupbQNZaisCRqU6Q3l66WuNyZWL851C5Y=,tag:QqofATSvT/7A3ua7f4uCGg==,type:str]
    API_URL_AUTH: ENC[AES256_GCM,data:eG4iJP4SWH04lMc8e3/mHvm4tBPveRa/vg==,iv:Snyw7C+2NsmsBiA50cmsFGMkYWLzUdfaB6kHf1XUXSc=,tag:BevCQ6EImW58n+BhYbtnhA==,type:str]
    API_URL_DEVIS: ENC[AES256_GCM,data:f0xclO8Yjkaj2neYjYU773keVUS2gCfJuw==,iv:Au4GiSPrIc8f7RwEufw+0udn8TnNSJQ6VFX4Y7LJlZk=,tag:X0zSoixuwGbP49+Bf0wM3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQTN4YzF1QkpEa1dpam0z
            dVpIT1FYYzk3RXBJRndUWnZxa2UxUDZBNVZRCjdRYVQ4MFVWYXZiVDVVdjFhSjk1
            YndnYVVSTCtlWFcvd3JuTThVaTkvUHMKLS0tIHMySmorbU54bjRnU1JCcW9oRFIv
            S2NTZytvUW1hVE55aDl4d3VvVEtJcTgKbUwcD6nXgUib3Xtli0gyEn9DjKkH3BEF
            c2CCuE3GyhzPIIDSeWS54P5Vn4Jv4hkrWX38gCcOzFWJVIeq+dcd2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:53Z"
    mac: ENC[AES256_GCM,data:FMLtmfv57eFrDSkAQVx+FogXVosXbbKlJVKVsME3X8cgwfS7tb4nIOrFbLGKSMG+YTuj2cp634ah/LwPz0r3GgwO9sLzWmjTDkWQYS4eFcBFInxp8z55zj1VnedDmOkugY4MiRdl1UxVzymcs9QeiBbmuzruAj5hUnxQT+TsgS0=,iv:9++RVxKrgvy7APRS7SaM0w3I98BkWkg3YDl1WFRzzDw=,tag:jMBqfCHZ1AN6KwGdInPN4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
