apiVersion: ENC[AES256_GCM,data:+OA=,iv:DGhvb+eoGO2zfROmAIj9ywTmEUBs0vjcencNaUk09cA=,tag:cGcDfgCtjiqV4Vsyzv9UtQ==,type:str]
kind: ENC[AES256_GCM,data:sIbIC39U,iv:7uAor8tn/UzwS3dwX1Z3YgWhvscI2J64l7vynZbliwQ=,tag:YHvM8dCu+SoWPAsKZfeYWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AbM34qy5KZYJSPpxJ9uLXSFIAfmyFlo=,iv:03y1csZ5oUXCV/T1IOdB0OPMONRWaGZt/eEEVXME6vw=,tag:J6MMZmCrVWqp3G7wkxKSag==,type:str]
    namespace: ENC[AES256_GCM,data:ilOKgQ==,iv:7vhzuam3rZgnhzufMf3vD5gIJTDtpOGSBm/W/wlV0do=,tag:G3C3pNKwqgebvV1o12/Kiw==,type:str]
type: ENC[AES256_GCM,data:PkBq068O,iv:0LkGsQI5ihVdAzc60kE80TgYx/GUPxJT+oof0D/Xads=,tag:dVXr4r84UbdlHXibZ5TWtQ==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:okjf9Ox1EMrMF3T16jxQANZTYiBdTBpzstgNHkFmGSJHGiX33fpqJ0L8AsyPfH6nDI2Fq+MILCQYxsvu84wtzv6CGdiEIgcqFwnvYFJQ9QvX0JQUz2PEj55PprdPHSBe6UcJa3vaPkTrgaHLYjpWV1Pjj/dIOUZGlw==,iv:LhWs9DZBGkRw6wabUxY/WKNBqmVfYXKB2l1emhzrSGM=,tag:jOf4+LIAxZscrmQXvlwZEg==,type:str]
    PORT: ENC[AES256_GCM,data:eE/CAw==,iv:zHV16CmGmwOdeBkfn2U/VPzOXoC+m4uCeBy+HJiiCig=,tag:cqDS9BDJ0DT0FTBWLAxfOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVHY2eW0ycVQ3RkNSMEZ4
            WFBJNUQxYmdVbFVhQjIwVjdzQXJqMlRUNlcwCk9IcSswejQ3cGFrKzNnc1NsT1h0
            MHRNR0ladHpBcGczZHkyTUQvaW5YVE0KLS0tIDU3eEVLSjJGdzVPckZ1T2VYS0lp
            TkNVNUtaU3lpaW12b3ZyODZFcHR1NkEKoo7sLHtX+qCwPTA/tZxx5OQiV50WG78H
            W+rQehfBbPzbIcn+ZRTHObUjMw5OUIGYwbDFAFum0PNdoLBmoULxOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:54Z"
    mac: ENC[AES256_GCM,data:u93jJsJ1sKdMitv3WCr0YTFnSPnaGxpJbX3VDi3H37/ZjLO65dJXO3mxXL56VWbs9lakeyVROD2WroAHBjI+C29rGnKV9uZzbEpBRrWYSOtwcvoYKYwBRQSWzIiE9376/nk3YZDyotwYaIF5ShFAK/ZNxb2bLQAqZMVNRiTImSQ=,iv:l1LPvWptKv8MkDhyi1daHvQJCOMlnpQ6q/FOLIt4KDc=,tag:Dn9Z6xJ92u/R9M0AzXstwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
