apiVersion: ENC[AES256_GCM,data:d/0=,iv:E70V5wnkdVvO/hoJQWKNkCIc0S3ClfyGnnWdyzJKLlA=,tag:ZKd9+Fs4KkV35+WvINSBxA==,type:str]
kind: ENC[AES256_GCM,data:JDxAS7U6,iv:MkxxQ1hnMsqfVe2Cl015ZJWZShWLwc6SNf7HcFeS3JM=,tag:XUg34AQDIOZXz19lGdhA9A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cBRGX7Rvd/Bypvq9ufsUv2TLSUoOKOI=,iv:C9YZjIoD1C5N951raNU+Ba+0U/R6BStM/E2ab8xAJ2Y=,tag:rHJ4IZwOmbjJfHsQy83pxw==,type:str]
    namespace: ENC[AES256_GCM,data:kQLP+w==,iv:1bpsg4b5NeWa8NH3rnSYbWyyUgnFC1U3Sb9UV3JU4VU=,tag:6PUvmqsb2b2ycEJqKvSc5Q==,type:str]
type: ENC[AES256_GCM,data:6v5Br20h,iv:OkaAczGKDcsNx9ggoq0dgZvobRasAFam+Os47I7dGp8=,tag:Thb/wNXmJR5x7P/9SaDY/g==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:lyd1XYwfIKI9I9E2Lxx7/dLkSO7GWpDCHOrPtGmeP2PnbUkzUtnBUhgQEhdHLVkachFsnE5Fxvogiq4UgJ5Y/ZTdRC/XZsG8RS3/bsloo5RJsNYbAtT7MCtES8ghuxeA0lTMWi5CuT2VE6VlBwDa9d0YceumnbXbQQ==,iv:t08L0G3W2YroufWg8Cpyb4yoqu69G/ewl+NubO91trk=,tag:yxmO3EkLxWNxsqPUTwKsvg==,type:str]
    PORT: ENC[AES256_GCM,data:ZVlR5A==,iv:f8yE8iXRohu01ABOqjYLbId7lcAa339R4Ky02VxHekA=,tag:XNdzJ8bJE+CkS4y3g6pvPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ240bURuSGdrTVhRcndB
            eE1YcHU1U2cwWDdhM2lJSC91REhEZkU0QVM4CldtZ1JLWTNlZDZVNW5OdDcyUHo3
            aTF2RXF2TUU2MlFxWlM5MUt2dE9YWWsKLS0tIDJVRTJuQ1pHbWh2VE1LQlZtZkIr
            MzFtS3hRbU43enJEaUpac2lldVo1TzgKb2iYSOL1HYy8uvJsGljpXUXDeGLt3g/E
            dl+Z0wlHloXcLUdL5LnaFXkQ+sm+alDa/1tdgPVQTlC2Luu1A9iVkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:49Z"
    mac: ENC[AES256_GCM,data:GolkkUyMcfqM67zH/m6hmB6X2gj0dvbZBqR5E0rU/tZWgfJifc/GVUzG1z20D281B4RuQAtx41p1eO0vMFLdaAbUQ0iU0pb+Lb4Fvx4O/yel6e6pT/Vbd9cJMcii/oAm9zNEJ3WTcxw/dmTo1of3o8NHghW+4vTcd41AJ1MPB40=,iv:rtE5QVCEmV9OBV/BrRTlkvFwFaSKTBIEi50urLvLcew=,tag:HP897h1i6/JS+vjJ6LRVbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
