apiVersion: ENC[AES256_GCM,data:2cE=,iv:2iOPUZCKqARWzhFpJF3DcxmjQ8H7yrU+IrygnYpDDT0=,tag:9szbpVnRHJRXsq0v+IjqCA==,type:str]
kind: ENC[AES256_GCM,data:Haf9IGow,iv:YqrjrpIqwgBmNGO03yN6IwMoXP5I+fwQ2MuCglmVV/U=,tag:8MeVwzYNeAD33D4gYtZf7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Dpahpz2OMcA82Q984jTs+YvOs7IHb1c=,iv:6iRGDY+Qykj4dRgiZiyuFZvxpA0E9o2s/ilvFbGVpHs=,tag:N5Cn0ggwteXs1agx0px1sw==,type:str]
    namespace: ENC[AES256_GCM,data:+mrr8w==,iv:FW4+azqya//5jaBGI5bchbgaAXtMbztCgxkdXu+oddA=,tag:RzUrFUOxpYxA8v+gU8A9Ng==,type:str]
type: ENC[AES256_GCM,data:nND/4qwJ,iv:8BRL6KdC37w6EM1iJLWIsOi/CqLcW9xNJj4f0HG9EyY=,tag:GoJzWQQDHXVYbv6jagWYdg==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:16X86Q0IOZGZYk2p2GLhpZotOK8pXCp4y2nYL+h1HvHOAgRjiAZge9G7zYOyv146MObiCt1PKYmEN3ff/jArkZES/4A+ujI+0DQxOe+3EJkTTyzOQ7tpsFnInGtxWpQONAQjiKTYvTlVBGvVQ24HblP+SyoSxBxO4g==,iv:1e5olG86Xfmr//r4LW59Q+MpuY9cXsjq6fQk8m7OpyE=,tag:BmURSuZpl9krAVG1+vpH+g==,type:str]
    PORT: ENC[AES256_GCM,data:1Tg6lg==,iv:mMLYpUpw0sAB8VZt/5fi7QsDi/OY0SiDeWG0I1oYqK0=,tag:ng+9LgORY9i7/sT1GR8rkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRTZ4YUZrTEI0NjVlZm5y
            MnovNy9nQUh6akhxRHVvZStXS3dMWXU2KzFJCnRlU2ZWQ1FwWGY1NzBXdk1xZUFh
            TFJXWmFnUmROeTJjK1pFbWxzV1BzeUEKLS0tICt3NFFVZ3ZpWVVPRUM1eVNHeWZp
            RnNHdVBlcnVQR2NxYU1waDAxQ0Y2VTQKqji1gqxk8cgTFIT4FRNmEIvlAue44RR1
            3VGusd5LMZSgGjpFJatQlER4keqUa3Ng0K2lwxr/6nH8i363d/cjIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:51Z"
    mac: ENC[AES256_GCM,data:Sh4TKU488zizXHpNxEsdg99yLJ/j/igqZ5TyiDk7DMxBNoAN8wCe9GtumhCAydL3GQSPG6qwCebZw693mUYfT0unvSctxvexHefurWuHFxA/yKkGfgT+CujeqM9u3cv2h6crVM2wS6+BGV8lp7c5gW+4qciouTp5hSBn3TsAFhc=,iv:mDjrFIeARqhbaj08RXlAFePmrPiklIQzu0PQVGdNBUc=,tag:OcTRlnDoC76GFeysVgFYjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
