apiVersion: ENC[AES256_GCM,data:lXQ=,iv:E/8Mh4nk9tdqMSjylz0AmCk9yvOWU+XWAeTTQ+Z5xl4=,tag:6WyxuxrRxrXehP+uN7IrXw==,type:str]
kind: ENC[AES256_GCM,data:QMSCUkbf,iv:G6c9UX7I9Id9bWGBZfesxOapgSbdk8e9q7etp/Hndiw=,tag:QoBrEQEquI4X4SUrksvx6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qAuwg4AZCxe2t2B8U1nuZQ==,iv:TgAvHtUMtjsG90sPAKzQeGMXerVYFxXmyQgvdWjT6RU=,tag:Pb/LZmmCP4Gw8AnIkuhYuQ==,type:str]
    namespace: ENC[AES256_GCM,data:hFRn1w==,iv:d8yqznnVjDCqJBlYtA+IkFsZNuHZqF2mbauH96Umq0g=,tag:VQBJthsfaL8volazwBmjkg==,type:str]
type: ENC[AES256_GCM,data:6QvqS+n4,iv:N8M3SDhzIH4T5px3XLJbicEupGvqnyDuF7ihuvZw35c=,tag:5/pS8DCaXv8++jBqE8mDlA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:DLjuvPj+Dqp8MtwMP1I9VdOOoM9tja3biw==,iv:pdZ+p1Lbc6tjOaASmv/Dh0jOCkMqhhjsZlCCxCV2iq0=,tag:lygVwZbCU7Yl2K6GGCqjgg==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:BrB6626UFac5QwSBXGCHHiesp60n/Z1XQA==,iv:8LrPTO2fPIYfejI0BSx8HYq2i4K90eim0Mq+I1LQ468=,tag:dQIwHj0GMwqla5Skd2j2Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcENTS3V4dWoyeXpoMmdT
            Rm44bXV5RXVWRnNJWDBoeDJzbHVqbmhOMWxFClBPeENJMHp3RVRXM0tTQmNvNnhH
            NXFqZ2tlWmlDeFVyNmowbHBuOEdjd3cKLS0tIGwwU1R3bWIzME9kT0dlUjVRWms2
            Zkk2NnRzblpHdmVVR3pjeHpuSGtteTgK1KezD737RQrRu3+Y5aVz52KMUXIP/0pO
            4ZVqtTWnkiLBn3w8xis0Uwj//ZBInHtCiPZn/LvzPChDjDGHB//DdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:55Z"
    mac: ENC[AES256_GCM,data:CFV21rqEDjRj2YgWQj5biQbircPvjQwRpWvGaZAU9c5whz408ZKaCWmNMoUdGJ/+uEGD36n+tSDYnvmrZpODsqmRYufKUi2FDK735oEJ66lo/GuaXRRCfvrRy0yVF1hY1btiMzcA1hxjsH2NaRFKuugKgYeP+gNX4IBMT8pOmBQ=,iv:xcAfyfsXwm2xBPYL73ORIXozVPGvZHlcUx6KCs047tk=,tag:A0WF9tEuwLeu+8FmEapTdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
