apiVersion: ENC[AES256_GCM,data:nnc=,iv:AjCUcJImCqlxfGH+/yWwbzVkCkWOr9hwIB7JdVBe4CU=,tag:LqIaPToLbkPzl+KSOjCppA==,type:str]
kind: ENC[AES256_GCM,data:jok3gVAD,iv:xA515fsL8WGXHlJs/R+xqPH8fU8Vd0Af784gVK2VU7g=,tag:+DZsLWQ3oMMjIhdu6oHgtg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n08xHREgK7++LmyoPa3tMA==,iv:y6t2Xsx6P3b+E6LT2kSRha6rUUada0kA2TrtNjdPByE=,tag:DifABQx0DaA1ttqxpYT+cA==,type:str]
    namespace: ENC[AES256_GCM,data:xPo0Fg==,iv:QQZ7GqIMvZ9EOtfNUL3ZGExDYEjzHkU+TbQJ6xxiroQ=,tag:RTO40DH3ZyeF7rzQaIzesg==,type:str]
type: ENC[AES256_GCM,data:+7b/ga02,iv:Nh4UU6YDtFQNYO73G1JolpW4/LHPMdPQrN1MVgF9oQ4=,tag:rUy3RoZS/wZ1zEFC8dn3aA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:SMpW+d3cBMSMlaA/3g/58reTMoLoXYO5Kw==,iv:N1G54AroVyzv6Y1Tni5+Mt2fnDtv0CfhYBV7dhTuplM=,tag:pQyQ8jsZcW33lIev5CwKGQ==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:hyMMidyKCFH5o6BeJiD30MWFonnsrGbWhw==,iv:6fSHmh5xGjyhA9t4pPUy0CFhU1D9avIrvgOUbOvRRmY=,tag:2ki5HDzPcPk9Dd7MFIHVkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUkUxRjZnOU40VE83TnhT
            NDE2Z0pYUVBnZ2dRZ0ZPVjZDQkFkSWFKS1hnCmlnZzJYTHF0RVptYjFSaldOSEw3
            U3c1YmhlRFRDWm53bjVaQWlQZUdBVGsKLS0tIHNXNUlDTXN1bU41b21qYTJpeVFU
            YzR5ZUdSZ0ZSSEl3cVZmV0VzU0JHNEUKUeLWqAc8fgpUPfOqvT5BQsxwSl49hLTa
            xeOa/H0kqyz1EwuXwjocs5LK/jsqsJtPTJoayFMPAusSmRQ4PpYcJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:49Z"
    mac: ENC[AES256_GCM,data:axQrTUgPcPXEjxp5bpNkioJQT8PgamIt4sYFOw6F0r0r2wnzKvXyhZSncWPX2YBi8hRFugt9VmVoE2ohLWllV9on23+8Z8qCP+OAEaO1x6VG3znOWsk53qMuu+Rvbg1sjM4RV2jW5tq6+oBa7SrwGQ1Eb1WP4/r5/lIA+zCBKPI=,iv:lbPtVKkmw9eeZPkZaCkca5Pk34WCOfCjwd74iqzGhYI=,tag:BESP/dg+Gkv7BeDsAcrDWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
