apiVersion: ENC[AES256_GCM,data:5rc=,iv:+Gk1509CRrks2kotwpfxaldzdU2oPalkAPgHBdQXTe4=,tag:EPOiSPeptBiUEWV6dr+0rg==,type:str]
kind: ENC[AES256_GCM,data:SKPoXXhI,iv:KP2Cjsz6xHqTyfSdSrF+I5QTqC8ZEppom2TiFBcspvU=,tag:I05FpjVybatxgf9sbKslEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DgDOjUfGhjSuPqXUuIg+qg==,iv:UvylntJF/AVZ0t86M3YKXuAgdUiPBcOJnF9eg88Vn0w=,tag:P7DgmusRN1keQOSZlo3wXg==,type:str]
    namespace: ENC[AES256_GCM,data:EboJFQ==,iv:csx3NxTEPCYn7+ab+Z0FDM22pDYdFzWoJfOJOcb+XNo=,tag:hNEWgIalmTf1x31tOoStzA==,type:str]
type: ENC[AES256_GCM,data:EhL/m3TS,iv:6jngfadmjAVo++aGjEu0r9+2AvryC8HVFVUYNayUGYA=,tag:QgyQwPfTxDkmr6PQuDjLeA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:EGG6wVYcyNgBGrY/egHL0jpWTTKqxhGbew==,iv:PDRGesoeQ84NsmZx2rKBCYjvdwPy+WTysaMR8GgtiOU=,tag:ObU206oRl2muyLCk9yw3GA==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:pDuIRL6PZLRgsXYVFoPs99dRZQboVg6afg==,iv:2yr1MdU+TUWmrT5r04pQlUOGd7o/jmdmFjVsoykLoDo=,tag:YIRGIbvSCCEb5WkPPwxoqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcStEbzVVazlKK3E0ejFL
            aUNwNnpmTzUrVmFxWW05T0o2eGQ2Q3RyVENZCmdIUjVSenVaY05PU2szT3MzalNq
            Q2RvUFN2aGJHaTluNStPLzdkeW9PblEKLS0tIGphRWJBcTdiNDdqNFRucFlicGVI
            czlIU1VYTTFIaG9Ob3ZXbzMxSmoyS0EKiPBRcOjwsBgM7m0j9LSbk2NLsDFU0u8b
            shGvEpzMFS+bikWihgQjeoCjtdL/YEe67Q9aU5hKZVjiuIQcXkF4AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:07Z"
    mac: ENC[AES256_GCM,data:50wkl1VaE2g43E/mHkFjkDG8n6x8NGjGgAQfwy3CgP/YXfvr+UsF/QTRR+TyZ4hONqRTGXQrDP1zqMX+T5W0l2Nu/FEVc1cFY6+sXXzB+q6woSKc66o48KuNjwYs5uTBnIENp+RRkWgJ6vef3M7FpTolZVeJXZ8VLeAKbKIZTEg=,iv:EcNqMuK6X4z3ehtbxdtWgvQg6Jj5le+yhh+SjNFVMzY=,tag:P89rShmkR0e89dAOVwSAtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
