apiVersion: ENC[AES256_GCM,data:hbg=,iv:fzG+9Z1wRPBHIVe1T9EL7uwNu39aSGN9PfUcyvRchqA=,tag:eWg3Ex+v2I9JNCuPPUE0nQ==,type:str]
kind: ENC[AES256_GCM,data:J8LseGth,iv:G+JDom36KexZAbI55ryWf3m4H3DW7dEk8ncEDIXuRmE=,tag:zwiyUR/ZV7B36TeKYYvyLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7HHX64AX8ZzpbSZT3cQ=,iv:TxuZT7U+H0XbHQMyL/4ufnQcAges4SNk32+rwsKfvYc=,tag:8hHH2vzX9jZ+TXCna0IWAw==,type:str]
    namespace: ENC[AES256_GCM,data:WZZM+w==,iv:Io93eRnq6g8yghzXpNUe6BKwZzhWKIY78CHvvjqxP8Q=,tag:QQUd9vuumirwWxpstuVQNQ==,type:str]
type: ENC[AES256_GCM,data:FFPB4IIF,iv:xqeBya/JJtVNaY1/rAh/KfFbY2+N0cIL8v9Jv3XhDDo=,tag:sObNmHylDn54blqzblc8tw==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:UI+jNQ==,iv:4njDdtsqjamYRcFsgrH2so6AdV1qvOhKVoFdxhYoTmU=,tag:xdvO+5gt1kJKxTF9g4hKEA==,type:str]
    FOLDER: ENC[AES256_GCM,data:zrHRASpFpg==,iv:8ICup7C4jnWUgHrR5X4eU/7KlvDsFNdzOj+XJQAOeQY=,tag:eXaL8vZK6ky7Z+2roltmHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV3ZWVU5PTC9Za09LWEEz
            UDlCV0p1NE5zbmJxSzJwSkd3UlhjV0xyOXpRCjJXb0JHWXpNNE1rYTdiQklwVzlS
            NnVSTnhyY3R1T2FZSW0wbE1JTndzUEUKLS0tIHUyZ1hHMnVLWWtnS0gvWFliRGZ0
            cTUvajFWTC95bVpjZWRSWTYwa2J0bW8KqxFKoLrtX7G7atich6Plg38aCh6c/vtd
            xH3TfMm3ce++CUb5B2oN8Qe/R9sTLiP3nFs4xYBces7roWWfshkKaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:56Z"
    mac: ENC[AES256_GCM,data:Gqquize4EFOFbB7PHSiZhWd2svCp+WLyhrrTQxBVhlC1Drslxd+M6aJGh0B2hMDvXZYbZho9t5fXrmrODFX5cWCN6wzne4qJCNNPROTu6xPLCuJgFFM3PcgeF7lbvcfl+hI8SFzeubIrBnED+nTBa4QVdrhTo8GDeSYB/ue4Jpo=,iv:bUHdhV3bGFF93DX4iAIl41YEeuKAIs/r9G+SnFD/L8E=,tag:ZwtCHuP71oaoQngdrlkqkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
