apiVersion: ENC[AES256_GCM,data:1uw=,iv:b5iW9n/a7CM9/2kKh0fciV2rza5FV9vUH//paQnFzLo=,tag:erAdSWXDgHpPstOTOkTIcg==,type:str]
kind: ENC[AES256_GCM,data:0r24+fcV,iv:gacVgRS7K45qBqlXEfAEj/VBylHu9T+qC70GL8/An7M=,tag:5wWAyPUMqqOTNkL2lq6Q+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YQS216P5KZyZCOyteV0=,iv:T4IML24GLYTYhCC+ag0yl1jYcWSxIHDXe0s0J4EBFus=,tag:lKa49YoSREaPTrD2Z1HN1Q==,type:str]
    namespace: ENC[AES256_GCM,data:ciB9,iv:CbF+5O01FpsPQyqjiUpdmvWW8L/HbiCIqK9+Vc009g4=,tag:t0IfQaDzeecaJUVRuU43+g==,type:str]
type: ENC[AES256_GCM,data:9b7IeVzt,iv:j5ZAP0cxcrMMiAH5+9xobESU7uJQlBgm6ZYoeuiQEnI=,tag:Iy4mW0pGUuF6Y0INPVTG5Q==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:oFAdGQ==,iv:eqA9KoOQLi/3lnkRvtoG7fhwFa5x5ydqzGjr4QJUHZI=,tag:FJaeoXlGcqa//oZEBIzFTA==,type:str]
    FOLDER: ENC[AES256_GCM,data:0P5a+M660g==,iv:/Fxrxf6UWXX+9U8QIIomG8ZSO9P57n3jXvv5um4gFGw=,tag:OIhCanY7dEubGchtmaUHcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSU1tNTM5cHZyVEtWcjAy
            UXRPcDc1K0tEYXFkTHF5TWNUUXZQditSNFE4CkM3blVwZG9kQ2hlQnFkSVhkOXlh
            SllPN2JQRzNxb3BSdVRIMmc5NjRaMm8KLS0tIEl6KzByZGVwR0M3T0M1a2l6ZW9m
            Y0h2bk1VV0FKeXQrNU1TdnFHZzBwTVUKgsP0wseas11u8Bu59+hLZsHvknAf5/qf
            FMxBkFG2CDUlCQHzek/wItf/LqcOFYctluovZUMCIH8A5rGuVkoZLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T17:59:18Z"
    mac: ENC[AES256_GCM,data:74HfSCwX2rPn+WmKB92J4dFJfpAYNmL0tflTRunwQg3Ots5ZM7yfunIM6SuOHrTVFD/6Yxl5N00LvjMOvJxjD+CntznAekJTaxd4FVXpqlXDFnXf5xrrXbG+x0QK2qGPsHHAzEqJ08WUONMXEppTEkop2DXrk+eepLBby17FYZ8=,iv:QHWyBKCzhJaGAxEOywZka398YXfAszswx/lKJk6fDqM=,tag:aU6jeeNIZ6Ax2NLpErHJHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
