apiVersion: ENC[AES256_GCM,data:XUE=,iv:k+4W6ajo/jpzCC5U2LOFNhdsZOzOL9i9m6t8WfwEEv4=,tag:CVdqg+V0EJtPWuv5JaS01A==,type:str]
kind: ENC[AES256_GCM,data:cgdBYpHn,iv:KkVuJg93qohoz4YiBgEw4ff0gPkdeO4sT7HN4GM4ZsI=,tag:Wf25x7s4u10EE1b/jLlBew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UGRLKfwycDAMBJw97FY=,iv:QWSHU2UrfgDap9V5TvftjgbvWGbZ4cTPOsfeVitEJlo=,tag:TWX6HlICLFxQS+M9/QJQXA==,type:str]
    namespace: ENC[AES256_GCM,data:jj05Bg==,iv:9rOzoarhCrRSNU1Kyw8eEfy8XXcelmOVgDJhAjQDNoM=,tag:ERnt2kNzDOgvhBbURvUCug==,type:str]
type: ENC[AES256_GCM,data:/FCfBcqJ,iv:uAcn5EN/HcFgf5qqvFrKFcE6Zie5T/ekZVZIh/5PRuQ=,tag:8zGOvCMh7eLVnichmb26wQ==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:8Zpu8A==,iv:7QwS5yOCS5Jk+RcsJiTVTkuKwzye6d7dnEZpzPKRm74=,tag:vMQFd0AU9boaKAKIRQ3Khg==,type:str]
    FOLDER: ENC[AES256_GCM,data:6GaofduzSw==,iv:AUU+S5jipOhSRdASu5iJn8SIoRFQfqef/S0DjV9ZKDM=,tag:peP2v+Hy5Kv6o5Iwvt08jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRnpIak5wUXYwekRaTnVS
            QzdGUDlRNnU1ckMxQXdIVnBwa1RyZmw1QnpJCjZCUTg1d3NWSkpwREowd1pUTEht
            ZWdNYjBQNUpLbWdUZkptYTlaWVBSMG8KLS0tIHJDcXVtSWlJSzZJbjVjSkR4Y3Ev
            STIyMnJxM0VpY2Vrem9NeG9jejJWMDAKuXodw6Xx4ks2faAPgYBZpFMbEDcy5suK
            oKo4+ar8LIloYDrtBuIpKNFBSTv66WMu6+P6U+f9kstm4If2fzlGzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:52Z"
    mac: ENC[AES256_GCM,data:951KlKRo9J5PMkcJ7UCQ5aYfw8gwHxV9Tc8CzoujfdlbA1ZPFPaKX0JpulFExB9ilmuwkIOw680nq8E5s1mFVR8gml+AnwjzxBlEf+g8RfPpAp/AsvPLCrWiE1l5ANNsS85T7fWMGt43Zv1si14MQwg4lEFeQz3vrZucKojTw9o=,iv:MUuJzEDDb0NJ4bgomAnX3w1yWsw6AyMyInCq4lXwCio=,tag:1mk3bgQISJjUI6HS4sJYCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
