name: offre-d-emplois
app: offre-d-emplois
replicaCount: 1

image:
  repository: 192.168.100.200/pfe-backend/offre-d-emplois
  tag: dev-18

service:
  type: NodePort
  port: 3010
  nodePort: 32010

secrets: offre-d-emplois-secrets
