apiVersion: v1
kind: Secret
metadata:
  name: github-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDcGJHYzlYWlJoUVorMkVhSkRDVFYwZ3JERzhPaDNsWHBHQ3lhcDhEa2k4UUFBQUtEMmdhKzc5b0d2CnV3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ3BiR2M5WFpSaFFaKzJFYUpEQ1RWMGdyREc4T2gzbFhwR0N5YXA4RGtpOFEKQUFBRUNLK1BXWGxMNlRPbUdQVUg4Qlk4d1hVSlo5aWo5enJiZ2Nhc3hzbmQ3dEhxbHNaejFkbEdGQm43WVJva01KTlhTQwpzTWJ3NkhlVmVrWUxKcW53T1NMeEFBQUFHV0Y1WVhKcExtNWxjM055YVc1bE0wQm5iV0ZwYkM1amIyMEJBZ01FCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=