name: offre-d-emplois
app: offre-d-emplois
replicaCount: 1

image:
  repository: 192.168.100.200/pfe-backend/offre-d-emplois
  tag: prod-15

service:
  type: NodePort
  port: 3010
  nodePort: 32210

secrets: offre-d-emplois-secrets
