name: devis-en-ligne
app: devis-en-ligne
replicaCount: 1

image:
  repository: 192.168.100.200/pfe-backend/devis-en-ligne
  tag: 74

service:
  type: NodePort
  port: 3012
  nodePort: 32012
  
secrets: devis-en-ligne-secrets 
