name: authentification
app: authentification
replicaCount: 1

image:
  repository: 192.168.100.200/pfe-backend/authentification
  tag: dev-11

service:
  type: NodePort
  port: 3011
  nodePort: 32011

secrets: authentification-secrets
