name: statique
app: statique
replicaCount: 1

image:
  repository: 192.168.100.200/pfe-frontend/statique
  tag: dev-7

service:
  type: NodePort
  port: 3001
  nodePort: 32001
  
secrets: statique-secrets 
