name: testHelm
app: testHelm
replicaCount: 1

image:
  repository: 192.168.100.200/pfe-backend/testHelm
  tag: 73

service:
  type: NodePort
  port: 3011
  nodePort: 32011
  
secrets: testHelm-secrets 
