apiVersion: ENC[AES256_GCM,data:lPA=,iv:s3Jx8uIBO5qthxOWwQd0ebuu0Sqq418VwYJKcsWXF6w=,tag:cQRHQXhwlpqjHkOSSAA5oA==,type:str]
kind: ENC[AES256_GCM,data:6hbMhLy9,iv:TTzhX8dNP+PR0Su3uX18/Ibp9qYVF/lFTYLSwyjDzNo=,tag:M0SmDENuGiwIrAkl+imj+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:droeHXNSpbeL2zWJjQlykP5ZsyftbX/L,iv:/CTS2cydK14tR2lgBYejO6k+JxQ12Gh7p819D2Qo+jY=,tag:wW1UqBW8kYcpPEka1XgMkw==,type:str]
    namespace: ENC[AES256_GCM,data:aPjy,iv:jAbK0nQmvia7YWerO/p5OlMLQ6GSfvjVSxmLgyOMPfE=,tag:hoRjWPADTiP7otXIiSsNyA==,type:str]
type: ENC[AES256_GCM,data:mu8wC/fJ,iv:l+DQhHAuKMCPWlVnuFZ4Tr1JMEO260G3DGMn9lK1eHo=,tag:YHvFa21OhtS5KIN8wd5ieA==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:AZex4F/4s4Y9ifI9Llx2wSAaCtn03aF2f4lpQkcPdQgPnH8w6Fy2ithVoue6Cfur+1VRUIclsdTfEKbMRamoA6KhMm5BTHPNoR7g/Mm43tWfdrcQp2G9TN9VWZDi1ALQkpQTcJLNTqX0l76PLLQ=,iv:IFNCQvHJsiPY3mHBsZDgYLLng5mnbUks/d33QuaMh6Y=,tag:sr/NB1Jtz3FFc8fxIjPeOw==,type:str]
    PORT: ENC[AES256_GCM,data:Pb0pEQ==,iv:nA01P9E04pw5fs0ndPKGyGS1VkIPpqGXcZWHMOAshdk=,tag:lXSFn8Uzhikq77DV6VNT5A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:phb7KUYpNH2DL8oGkas=,iv:SItmIpJVAEiPVGVwMRBuMrd9mioX7keroSWwOKP7yVo=,tag:faSUDOoTekAkySvt9VYypA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMclNlOW8xMUJFakJsTWg3
            ZHVDYjJTY1VTUnBtU1Uzcjc5YU5SbW1VbEhJCjJad2RPODlkU3FuZmxCZVlNNUFJ
            S0s2TkFQbU1oRldyZUR2L3JhQnJXNHMKLS0tIDNzUXlwZXd6WHMvcENMZllvZWo1
            b003V0RCdUc2WEtENGQvTm5yWWVUQkkKC5J/ApBYCk4n4kfkYX04N22Mw3iTDzQc
            NMUkWCKdDOItPeGUG+3bf4t7ABQiRvMHDb0OzcKRA9Gm24Zreb1Vww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T17:59:13Z"
    mac: ENC[AES256_GCM,data:cvIGspsaJF4+m5zWF0OG5/ilYxwt6UmAtAHp2o/bSC3ZvipYflrsRqsEv2c/HNmKCfhA/NpQIcx0Jt1USBQgP1Bqd2hU2nh62UmXdiEDMrP37HfCQaEHHegyOr/aw7AeAnPRHY7ULUkXA8mAjwdHbAvDlfcfm7b6eA9yWAb68vU=,iv:fWf3XQsWDxb/Ae8rcPEzjzQ/cqeOjIFNtWMePkIp2SE=,tag:fAlygGBmQwyNE5AttnSErQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
