apiVersion: ENC[AES256_GCM,data:fLA=,iv:L36tGSqhCx4S8L5fkh7bD4dDN9yXGz9MIFHdGwAEgL8=,tag:QFWoxZwewALbTk6U89Uimg==,type:str]
kind: ENC[AES256_GCM,data:rVXGnIw6,iv:JqI6iPbptoWdDq11BnXHh6ViKGWyURtj1XYs8aCZIeE=,tag:fJZ+DnPiH3oIiwdY0y1ncw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pQthZTFBqIFdX/bG/kfbxtFd7GKz8j2Q,iv:Cczogqdn2NxHd1qq9/5FZS2jad7pHvGDwRhWMTo+bi8=,tag:EbzuvCrm5MmeqNvkfeKVKA==,type:str]
    namespace: ENC[AES256_GCM,data:dGiq,iv:/bo8n1G8iGuUyKqNdiDAIbT2mEOLDiLY7tgSQcv05dQ=,tag:Dch5ZcczAcSEAHTSdjm5XA==,type:str]
type: ENC[AES256_GCM,data:nt4/FYLl,iv:lnJxD0b3SqTkIuzi2jBk2btsbJ7AfKU6LAflfp50siA=,tag:rfT91sBkru6UxQyg96LwfA==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:orsZ0dI351Cxrr2QnGH83zJ7Cp1s6c/q+jRUNIIkVQ/Ypwr785Q2jlIXL+7dXCHhLHknFBwDaQCVjmcPDfXaPltu7ynFZrNW7ToEIGjyjkW0hVIp5BiCafuWKeUBU7HTdXVdIDEfv1EABU5pR/w=,iv:mtz2DqhDgcUhX9Wcac8jrPm7yCoMxDUGgqTzuR+UaoI=,tag:NS6uiTYLoe4qSUv7vXxRUw==,type:str]
    PORT: ENC[AES256_GCM,data:kUj/uQ==,iv:jfA2+4ePrNwRQA44b+h5N5SzR2eBw5ot/dTFzP0ERjs=,tag:sIGXwZNO7V6pm0LPTKAe7g==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:bguY5N9hB0XRS0dkkAc=,iv:lD386eMH0JB+rD3lDJ6eD/FxHZ27IaueYTjaEiQZvWo=,tag:sjWVjJOZOYXgR/BYfBORdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZjJBQlMzQTJaME1xcFJD
            bnNxRTh0TGRqTjEralhHVlluRGZkRmRoWlJrClBpc29uOG44dFgzOW1KY0RGRDdJ
            R0dtODc2c08rKzEzRkIvWXBsQ21QQ3MKLS0tIHkxWm9tQ2U3YmNRb2VUTDMxWFFU
            N3JSb0x6ZVVVbkN0YkJQa1lwcUVxdGcKMZzfWOwWxjkxi7aGb20TMhGF0M/BXOqQ
            Hzyq2zjLRmrinl3hbeAylgRsK9g/zHup3gv+dwN3FQcZK79vsOaHXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:46Z"
    mac: ENC[AES256_GCM,data:S9qTTJIXxJBOvSU/OplHV+P9fY4s4ss0Cit4NhP789ls0liQElZkOF2OTKZUBRiXFZqFWfIlbWJMXtmZQEIFtftr1SpIcuxJaSUK38zXGdsslwsBrpVZr6J5tq1hlI8VdkovEwiVYyI/fuSOR12shZKG/AitskRKag5vfwm8+xY=,iv:BxJ5fbD08g+f0xLC1xJ/DvYisrXXCIAxnHd0tzwWBj4=,tag:QCKr6QwPsMATpdvXqK8D8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
