apiVersion: ENC[AES256_GCM,data:/2E=,iv:3B7F4JUnGZUGV2Ew52ycv0psHJp9+OjwzvFvqOi3+KI=,tag:v/RTL3yKAp96UWuFaSA7dg==,type:str]
kind: ENC[AES256_GCM,data:CeWDI5mY,iv:FfN/ZirbOxH3suMhK6SoMto1D0MeaHWOT9PvTKsbATA=,tag:4u2tMRebAIkPcj8R8bgDIg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pmzSMB9Q7pvC9I0B8G73mXlfYjSKmdgD,iv:mCR6WvP7GsyjUR4AVeLE5ANVkZ77Fz4RCriScPFL5KA=,tag:Zfr6jhd4Qnj43D+nzizjUw==,type:str]
    namespace: ENC[AES256_GCM,data:EFTT,iv:t3LhmRnL3RVwMhsLfs2vowWguFkTqfdhWX5ULfwv7Do=,tag:o/ARKq6PvRz/5lRMaL/1Sw==,type:str]
type: ENC[AES256_GCM,data:GRgWUQO4,iv:sJOio8VuCccH5+XVd3KZ040oG2rHQcGg529Gx5KzKzk=,tag:KhYzHofykc1y+hUvEfJrtg==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:sBZIe1RJQmrny7xAL9eKrGMk4xdadFKt0hgIQtwWFXxHFBMMbtxkzpjrJHeycBGbN6r0DolMqHJtQOJ02tFljTlqHOf4hNyAOMDGOzY39kp0hSFKJdLCtYm5BeWUuxxJKFS1z1xmgrshb1aMC7Q=,iv:0uF6X1l9rZ+tcgRa1jV4oFyLQ1LvA0j6TbdRFZ1hyQQ=,tag:TKR3ZHXVKnInHvTh07J6CA==,type:str]
    PORT: ENC[AES256_GCM,data:p5/KZQ==,iv:OsR0dwRd4rIjR1mzw3et1stNDmbmt/DbeqweqbMyPzw=,tag:rUcS7MlTYqF/XLFygtFe8A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:9iusgC8VlIn78GuuZz0=,iv:X+HJP5VmS3o3nMXeEHnb6kSEfW9NMamTcmL5kcHuvXc=,tag:LQCH7M7TUhmvKoD7If62eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdkNVV3RlMWgrSk9xbVho
            NytpZGZMWmNPenoxZjRabHFQYkhGcFBtMkdFCnBhS0hpSjBYZTM3YmVTaGJaa2k1
            dXdSc0U5dThPek95dVl2Ui8zVGMrUU0KLS0tIFRNam9GQjQ2dUZJVnFnNXM4SGdz
            eWlpNDArbk9FUy9tN2s5L1NDMEl0QmsKz9pDvRyjhRog1zNhc0PcGrCnVVNPoIwe
            Z8LhhKvkZkCUgTKABfMWsESQ+HE+NYZirlEuXYk1xBUiw1/xXPXL9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:40Z"
    mac: ENC[AES256_GCM,data:aDMxE0RzkepJJ48QetyCyMDUK66ja8vfZL3It4zMLhAAnIEXMSk3QEL7PkG+AefhBqvTflwT81QX6RNkOAsCoSeelk9Qhj4oSBqvhKIWoxR0QuhuHVYR9uhmc7cwCOpP6rtQdiyMZjLZC/ceX37yHNhZj71QbzxkmaHBxj8S5Hg=,iv:p41Gm59RyP/W4wO25J8VbISNyaKCC6W+G5y/ZCeizvE=,tag:dd6Uf2WT7vTUBBzBtthFmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
