apiVersion: ENC[AES256_GCM,data:xY8=,iv:ZQom/ZEKYyeyl4q6KZ3GGoPhWSY/f60glKXUNG7GFl0=,tag:f5uyhsDphOyTs6NgRRQAlw==,type:str]
kind: ENC[AES256_GCM,data:GaToizEt,iv:KsXxP+vtVZIgw6zpApibpzDZHdNwx1qrLN5FlSvNMcU=,tag:ymAcIbmoqNqspbSfiRS5EA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qUGCPk78oLUqRerZk1/by0ZxBQWNaA==,iv:sEaId8qJEMCvZ3hdc6X9Svy0SevCAvc8JHCYF8SUJaQ=,tag:AxmNsCFlQF+VyWaSy1ihyg==,type:str]
    namespace: ENC[AES256_GCM,data:DkCU,iv:0HCLyp1OPD9v1Uwbs5yR+j8L2WIKONYzuDwfosbdQdk=,tag:4UmAZ+5m3+dTUekuuFT/1g==,type:str]
type: ENC[AES256_GCM,data:KtdBt7tM,iv:FiZdSpC/2PTMuB+s+f6GYRFEtE0+0tiQ9T0H0cvOEoQ=,tag:q3NLmnbozebUjOZEATY6OQ==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:CaJrm/sY4Pf2kfvzRzNCsR2WlagLQkPcPsuz1/XZuWzON5Qxc+ovUsiPHujOiWbA9ith3KhguEU+Z0qgT9hCSyKmY1fwXhQoZmUNnwZh59y1vTWMWUqPczwtsS3B+g+Soe7QkH7juAseUtMM6GNp+AsthUfRVWl9,iv:+b4oecLlSh21t70o7YAiL90Z1ADYa3PnYm8ypqUyAqI=,tag:xzg5O0QRkiR4T6L5yaKmNg==,type:str]
    PORT: ENC[AES256_GCM,data:RKD2JA==,iv:KGRwjCxHscEjNKKPHfl5LMr7mct/Xs7cc0A58Sl+x7M=,tag:5p1dP7feQ985wkYra+WOfA==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:b/nX4cuSwFBbdFruZUQXp9CPUC7qHgJN3J+DbHNOHXi+4aqvXCDTcaeiVue2pWq8ZLxzF3R111FDLM2eO2mMVAt1v1rT,iv:FX3AH808RV0C7W4Ur7JqLdi5oj0Smdd/Kryh0kFaJNg=,tag:ZykNW4aCOfvOaDYsO7/HDQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:jhXTgrPCkCs/MQ2OvD0oeztp9h2e48Nrgw==,iv:FEP63bucrou4Oe9CYSvlhPp7OGvSRKakgj2f+VISH/c=,tag:uBg9qSabzLoAuEESghMViA==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:DClLPw76S9z4kFZOvwIgYJA=,iv:RnBRYheV3b15N01oOum1R6cOUjXUfdM2bU2MoFbVfxc=,tag:a3Obps4WN9Y30678GikzRQ==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:qfky,iv:dzHoeDe70WYSTw1z6G9JPOIq8pcsFhxG03Ehmg9xRG4=,tag:5EP3HpVxdVl0cSBGavX6+Q==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:wSiIOOVn,iv:VQIRuR4T+23X46u9Jnlwsno1e37YiVxkCYbqzqTxwcU=,tag:MS0/uMhQ8TdKJwQbf2woCg==,type:str]
    API_URL_AUTH: ENC[AES256_GCM,data:xyBLg9tDKuVQLI0T9fvIGlJPr6Fnp3WsWg==,iv:2oGDn56zjtvwQQxy4QIapNGJWcIMXYsXCKZ/5LFB8vA=,tag:0/gv4IFRg4GQvgZ7IB0gZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU3FkU21pa2Q5bEt3dWx3
            RzVBQ3FkQVhDcmozdnRiVDRoTjJKRVkyL25FCmloN2FsVExvbFcwenE3QkxlNVgz
            eE02NENsYXRxcDJxSHVCR3pCZ0tHUGMKLS0tIDNlTlRLdGttNEdnL1VsQW9oMDdE
            Z0hCR3lROXhKMGNrcXhPRDkvbWEwV00Kx4LonM4jjSZZPH2tcERHLujZMQIaly/p
            HlAh6wz2AzjIcnPbddVWMtC6mV/GPSKCmhB0jwH1nAW969Z0EHd8zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:03Z"
    mac: ENC[AES256_GCM,data:sAnxOkgdoJnLXUT7TaSbucmd2L/8935bxR26aH/IWi7I9hBH5h7Kz0KViglfCp1lTqPVOTpFDqI6Ab+IIgfRuDmQbu12NvFWauJqUaV4luPJM3T0USX0TOxsMPuyPVRY5futDD915LQn1A9p0g8e+juJDT1wsTgpJ08rY0pl9ZE=,iv:ISgBNM3PEDv+Eb6Gnahl4sUSAPR+gSiVHbuG4j98qPw=,tag:oHo0t5A4Bd9YIFrUa7tuWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
