apiVersion: ENC[AES256_GCM,data:eGc=,iv:pHQ+68iFycFfd9asiw1hThvS0AFo01HFIReO7qxml2w=,tag:nw6ib9j7nqWA6DCBq063cg==,type:str]
kind: ENC[AES256_GCM,data:l9do90hK,iv:+K3kjSmVxzB9lVaV2KAQLDBYdQji+6tKk83FrrTGUjQ=,tag:aydVZUSJr8fAHubYd3q+tw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1SEVnhVfMQ5Or6C45zwqDvdlDR6gpQ==,iv:fEp8ZY7VlsTXvLGvxOyonNafneFipNHZTT4aIsw0cwU=,tag:6pNHirzxaTPLatns7Zvg9A==,type:str]
    namespace: ENC[AES256_GCM,data:3A6n,iv:pQ02XvMBZ4rEQzeNJyPzwfDJGo8o3g+nAdmmzZ+Awfs=,tag:jf+JmHbzvBIMHJKidmjRmA==,type:str]
type: ENC[AES256_GCM,data:PIlHaomV,iv:b6dILQMuWbkGM+r7aQyBB1TDWIYUEtStjWHdcJm2CXI=,tag:2ujqzFoSgN8EwpVc+HjVBw==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:gaN/S1YWcYzIGIP/f9MrLUDppfLoBJgiaP7mIzMCXV9RnCxZQD19+f6hufoEaDrfkM235q1DZqoKjRLMTsNIDUO71LSauljjBLAO0JcUFtBE1B7i3hFbExIdSX+avA/PF5zkBjrZ5Y6Yth8VLgpImMgr/WOdtTy/,iv:9ZGuu2j6eEhlp3fJzkHL/AU1t8JgUNBv5Zx+WnR89Vg=,tag:84OXSJ42EphW+stFi5etfw==,type:str]
    PORT: ENC[AES256_GCM,data:oBUykQ==,iv:OgsZ8vwzFeMC/71psIBTzcsOgUPpkMR9k+kFbqCrrSE=,tag:Cks2+D2A9m+6odw4TiFRLg==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:094I36PLC47jGcXcOt/PhDET5PqwiodoVhLt+vUVdEpAn9EMbBCwY59Aw7PbodpZi/hpcDjgRokGUoAHmYpQVCu2uJ0m,iv:YGmBwyX9XpXAKetN8yk9gWgkxmdVMd4xFg4m6IhVoNo=,tag:A60b6FuUmSccFEgZfwJ7bg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:KrEjveEMtHUnVHJbjWMbVo2uZySzKmFAfQ==,iv:aT7BXp1N1zP1o9RGrl57DBRCeu+Pzzsi9RP79lNiof8=,tag:OY2jMSudjtWauCK7ykAbYQ==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:pPVQ2EwARpJ5swYv98Y4p+U=,iv:uoSJYcOUY19VpMBIBf0+TlHZeWEDtH3/AGw3evhUHCk=,tag:N7tkA2FGnOr6Baf+nDovWQ==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:wcdY,iv:XGmA4Wf4/8trb6UtblqRW2ZR6ygygD5vGbqy9PoSB2o=,tag:KfZWX0bRr+1svq75TZgsmA==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:xFxODi/4,iv:05BYe9wqNV1tan8eNgxY7wwcplvTMLFpQ47xk6DR6xI=,tag:xhbVXzHmTuVbVvsTXB+1QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMDFEc1l4eUc4ekI5QzFZ
            bklnZ3AyNEJXRjlSdXNPMUYrTFFHbVYxd2pBCit2TzIvbzZiMTlvdUdzMWZqcUFt
            QkxuWjdCNEFXcnJVTVQ3dWhzWXBNM28KLS0tIGhpZUFvcllvc1ZhNkpWUW9UQS9i
            NnhCK1J1NUU4b2ZaclB4K3Z0OW1oOVEKGFEvNOLICgh2ZlT4BHiDQrJCCo6Apkd2
            BKWqZs+3Jxg+iBsEXd86GVy+8Uc/0ohNzLEVH4LOJeFc2dsN0z14tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:46Z"
    mac: ENC[AES256_GCM,data:EmuK7mdY9KH1do2ss3EoWQ7ZHO9+5mYXr0et/1UCRDBAuUjIwtBsqlBh9lRQ8OK0Dh9/yMqkLhbk7dC9bKPQqMmdGM7v/Z+ymocbXKQnHY3Zi8hKK0aw5pitrX3QQlIayIox9e2SGqWAOCR5Tv9MT1yFgEtWIjU4kjheLgUUg3k=,iv:jzkfa5q/FldbOG8vOuj4ahkBKJRrOTqx59aWG2nSTqc=,tag:3klR1I1PETbDVtBhs3DUyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
