apiVersion: ENC[AES256_GCM,data:XK8=,iv:+rquLMh3/G7OppFcmj1iD/Go+nsqsudsd0qvQBiXMMw=,tag:pLqSk1imoZdIgS6ucqzsbw==,type:str]
kind: ENC[AES256_GCM,data:3ro2XURA,iv:LumpmWDALorCC6aK+lzU6pyLj7S3hm8fQnyHROvLLz8=,tag:wCGJdLiISW1Sl7cKZttU7Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:80C0fGPHvWIvJpojPUuHWarUJghlTA==,iv:5NZdNNgA8f7/6FPlTvhkYrdfZUtal4Lt6uOf2vqfhdI=,tag:Z+L3a4HNwjbIaiEhjHvdZg==,type:str]
    namespace: ENC[AES256_GCM,data:1RLG,iv:yInNQMLyOP5I+vZXyfdQqyIn1z5dPBmpLEobjOGMbf0=,tag:paE/V3DxS7wWcb0f+1P3bw==,type:str]
type: ENC[AES256_GCM,data:N1SKpzYE,iv:6cIwmmfBnW3336SSweRU4y7c5CNWJPyXYtoV5kNWwYQ=,tag:uIZws+dAGN76v6ok8G16UA==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:Ah+MLu92+MBpNHzQCpgpTRhRLuwPR1t1TGcWUpYR3a8w1l4hJGcuSPyYi47NZAZpemQI5aFfoldkPnlwhXfPm3pVrFO3z+MjTQ2VMXDu6nqvFCEkAOER/I9/GFE1e8M23C7FKc4Ps9l/5xZYY+DwnBqtr5m2zakg,iv:RKGD79Qu6tH2S8Ox3uJ3MHdAVDHXtBkV1MDaLljqSNk=,tag:rRNRKCUXn3mvgeEsyH3/6w==,type:str]
    PORT: ENC[AES256_GCM,data:0UXa4Q==,iv:7idyJvJu+aqaUkb3pg25ELVIWM7to8Qt2cxVZhTQMUI=,tag:y9K/e8VrBLBsM2ENhJel7A==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:ABys9ZZwEK77LsK9HtCOn8l+oo7cQ/B7eD5rWCTdn+4wDwFIgRLM7NL76vWNGOxTTu6KmEyuq60EaYrQUQNaMWxm6tPF,iv:o4oCvgEVf7Hjdn/SveGweQ0+87RwXya2rBt44fIcdtI=,tag:9zgZUx/oWw2OUyjbH9fhfQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:qKmSDsTbWtJn2bKvhz9IUyk7tKy3tmfFDg==,iv:ySnWWdtER9k0s5iRnhhZvQn+ihDkS7SXHoPx3pL6S3s=,tag:RG6aRLb39DOUP9R9+fy+Fw==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:CQk5s9g7ENhtufc4PuBME0w=,iv:yaO1kfC7V2Q+4fkymeL6NOP7WtXs6J2hqcj27SI/bPE=,tag:8xab6SVlvQg2j32qbYjY9Q==,type:str]
    EMAIL_PORT: ENC[AES256_GCM,data:HO7J,iv:nc6COGk4+TRBmzkBMBoqMRnR80k6fC3T9+KLBXokC1U=,tag:bgPIjuI6m7D9F9MLgsWikw==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:kbl/NvCK,iv:rIEAmjVc77GO2OJD9D9didCxqB9MtGB69gPCCq1zaOM=,tag:WL0xdZFWaJyT2kWZAmdj8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaStleURLWjZOV1cxMzl4
            S0RCTm52Q0YwNGNJNHVFMmlLK1pSMVBSa2l3CmFwaXhnek9JNTJsdk9EMGpDRndy
            cFRZV0p6TEl6bFliQkUxS25UTWR4dGcKLS0tIEs2Qnl6K2p4ZFY2UnR5ZG5SQzZY
            WVZwU3M5Tjl4MENHZWgzMHhLOUxWVEUKLkTivehC/3f1f6OglwppMB04y1YkTjMB
            Yqkdxa8S/TTmDzh+fkav/FpERTUaBekNnaPvFMcr/CXZ9C9EjgQg+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T17:59:14Z"
    mac: ENC[AES256_GCM,data:uvhQxUSQ5ub0lnsDqVCOTai+O+eguGYURWjjPl9O2Cpqqg603mmIeDvoqCjPtxfUytTPLOi7sBh119l0JXEU0WMOgWsrXmqmyN8uI7ps1thpfOWsCmZ6tcPwyC1wmCUP7j/Y13l50aypot20wFMPnp+PbJKREpZ01XI/KRBKYCQ=,iv:Bef6ettj3gwuqmYxA9PQIDu00OuZ8Ftv54VIluxhgOI=,tag:Cii4Zd6tqHSSp9A/4dal4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
