apiVersion: ENC[AES256_GCM,data:A84=,iv:5iObph04vc0Yk6VJYPKKViIiJaDxl+CpTJl4VGurcOc=,tag:sNwdhfhTmahXP3NuunXLjg==,type:str]
kind: ENC[AES256_GCM,data:kEkaK85X,iv:0zz8xc0AuGTi6+yUwj8CY8sEWyPcPgY8aLmSvr+Ueig=,tag:XwKNaTV9JqPpph/oc8J3EA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QJBnGPxv3zwccT3NRMD7PgM=,iv:8XqaOutal+Q4Irv7/AQiu6gwtmZB0NgajkBKlBzdMKU=,tag:oReR83tn221YnI2yD9ROBw==,type:str]
    namespace: ENC[AES256_GCM,data:3bDh,iv:iIkLKsaFJcj60wMIjMZ4PbKKU9i9fgrwZP4Z27jux4k=,tag:+6DM2/cciv+NiRtf/T5lUg==,type:str]
type: ENC[AES256_GCM,data:4AvO+CVE,iv:TuHM1Il/SAZKyWe8j6kn9myjmR137Pjx1wQiZwEtVjw=,tag:YMIk1s/3GsZa/52ltHLtXA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:ZRwTshTCFxl8Z44tIaKhSJsGMAZmcy0lEw==,iv:10pCo2tf++7ojruMcthXX1tgzuShaV8srd/Fg4nnNUw=,tag:toweT6bash55Xe9CtJPfww==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:5rDOx5DWlAAxGHAGhSmTXuNNTlqmj487nA==,iv:DCKo43KWQnCbJ1Fe7S3fLI1HNpsyEctRYFx9n5T2Ick=,tag:8tqxj0F/C30v7EaaoQoRZg==,type:str]
    API_URL_AUTH: ENC[AES256_GCM,data:jjWrT0ZcMa7l0Tnqi6LiXD+bOXuYeObcPQ==,iv:U8irlMLeldkeLJCPkjBGdVrmYkeXLQstgLuJU0W7gOo=,tag:x415zhIqzfeDm/69ycZbuQ==,type:str]
    API_URL_DEVIS: ENC[AES256_GCM,data:X56t+LfsO951SjB5tq5ge+k/ddeDsoZqEg==,iv:J0ln5GDrxGJ+hZZI/4i9Y7JwN+Te5WfZ7TkIN7bYWSk=,tag:LL1qbPG85pu9urPcBTIWNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUkZYWlhOYXVzdWNQZ3Bn
            VVUwZjc2VHhEaytZMTdiQkJUdnVvbHh0U2hZCjlFUmQwN3R3QVF1Tm1hU08vZDNr
            VWRSLzJEcDBnTkU4REJuSW5yeklRVFkKLS0tIHJUOXF6dFhkNjdSbXdDSUNEVWpF
            R0YxcjFRdFc4WkUxWENCRXdPMi8vb0EKWlgBmDrm7DpcEK3NO/+eVpl7h7S+5Q9k
            AyEPiWwQ7PeWqDgGWllzYxQPCoIoRP9m3YLPdDThiz26eNH+a1TWUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:03Z"
    mac: ENC[AES256_GCM,data:JgTnlXDtYSXS49jwQ1QoVza9AsPH3cKu31sODP7qf6LTAZewA5QvDSY1mYHD3yiof6q69CP9qoLlTVi7OsPi2Al4/XXKYWXpNeYZhntCv6tO0Rh7kvQ61LOyNn4A4uUeG5Rt7F+QWm02lziuYST5yDpiOWPv5YU5gR5+0vmrNoI=,iv:RDE9bX5W8tmkL+57HyOqQRJh6QLr7THXRguwLogpHrM=,tag:vgN6a5TeGh8Ih1qKzVpfqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
