apiVersion: ENC[AES256_GCM,data:44Q=,iv:rF1pimRUfDo+LRmGxBXMKL9VhinB95u5XFf1BYHJ/Gw=,tag:mqXlYUSNJE2558KW/VNjsA==,type:str]
kind: ENC[AES256_GCM,data:SvqKOiut,iv:xLYfULJVh9ZJ9y40oYxPriEigpA3UCXvnkH/gFucv9w=,tag:RIvWzBj+puKXr9dkRj0fCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PR6TY0EW0jGngDTvCvzcRSQ=,iv:sRgdmTQtIIi+0lHwbgtLPp6Z46FtbgE5sk3Wj+c9cfc=,tag:mpWa9FN+/2ToK1OzG4OmJw==,type:str]
    namespace: ENC[AES256_GCM,data:MxDL,iv:rhs/9ooJ0ykmxJDf16NOUX8+KeNTzSA+sEAOXm/GV9k=,tag:ZJbcJnSgspmFokMu1jiP6A==,type:str]
type: ENC[AES256_GCM,data:SUWYE2Yj,iv:pcDSK7FOMtG1+AmgzPvrSaSXLHhfA0sJVTMrfqlFHjk=,tag:paKPX/hDU2U/8muOzxM3fA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:qRwIRXmixjkFMmSAI3RWLIvcQAfRRlhNvQ==,iv:j/DiV98GD78LudL/50r/XPCGcAoPg7sfZIWy4lTHnp0=,tag:XsD+nXHLwkzvVYtRj401gg==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:9bLa0OAiZ3Xq1QstQjo9DJnCW/NFXp/qfA==,iv:EAohnxJSFX5n0238XI3CjG4sG5g1+pE3MXvXPg/ovR8=,tag:w1AkftAS5EFA5CdG+szghA==,type:str]
    API_URL_AUTH: ENC[AES256_GCM,data:CPEtLR528m3dZGobp1x8fyCgT3eQBo1SGQ==,iv:2hn+TZQaYK01ZB2dN4vs+0CToSGXsFLPEkcC3YCemy0=,tag:28vEWjn+dotkO9wd2RgzNg==,type:str]
    API_URL_DEVIS: ENC[AES256_GCM,data:8KUEJso0RhAOPlMczXeWw194VuTGGXFQOQ==,iv:XuSqzsQKUJoFf9FZhmiVdiI7VE8Rmnp1RhCy/FshjQs=,tag:XOG2KEPb/+wQwtsppb6cGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQTM3UkFYSlA5aFFsOHN1
            azRKRUhEUmwvUG9MT1JOTC9meWY4N1U3a3pZCmNRcFdIVHN1TWdVcWpQb0JLUzdS
            N2E4Q3d1TUpTYWJtaFlsOU9pclVVYzAKLS0tIGZ5Q0dER3FIZHg2Q1o3VkdmSGlZ
            T0lJa1hhQW93RFU2QlZwd2NXRUluN0EKWdLE5fsSFZOw0nHjr5XPBUg8KRL8VQ7V
            6LGULvspcmrwjJZaH0zibaPF03anQSYpX72rEWGBhcmJ8abBjguv0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:48Z"
    mac: ENC[AES256_GCM,data:PK8S22X5qR/5FwWWZz3K58nBfmdw5rVHdnJXIHVuCES7QK0oUuRKwFpyL9oc4YGZVrvi1y4xtTw40ZHVwc3vOaSFOrJPwXHZZ+Kzcw7voBd+He9G/BVYult9ODGCyIsNs6Y2U/g7I/eXvZwBkKlukx/1YQrclFPN7MCcW9lFMYs=,iv:jX5Zmfs4xAct8VkZStTdAUPsKdWgudHjmQrQHUhGCUA=,tag:jVGbz7aM0utsfvuCRHyq8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
