apiVersion: ENC[AES256_GCM,data:7Lo=,iv:F3db7mb2n8YuZIOx3IOKEew7DyFneNMNp1hpn8PF7G4=,tag:o5Nf5YYK2h+DzuBAP/rz0A==,type:str]
kind: ENC[AES256_GCM,data:5ZaNZ0Md,iv:DfLo6JsFm4UXWkAQWMS0ybe+XgSgcGCZP8h4hjSenfs=,tag:eL+Voe9yV8bky9/D1/Ba7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/TcxPlgiNShNgZVmaGVHtcI=,iv:+UDPKE/5meysnbo2hg9RmM4lZMqYMwcmDexycztNCds=,tag:yK/BTQ3kdNS+ZpbcTGZQMA==,type:str]
    namespace: ENC[AES256_GCM,data:Lexa,iv:HTPt9GMrUm/5a1IHPkAOdqmbT+uWKzUg47DtRMjxs9A=,tag:LgeR+CYPNLP9fmzWwY9wQQ==,type:str]
type: ENC[AES256_GCM,data:HPwnBW1V,iv:Op/R+whR20upHYEh0jQbB7qVpcJK/pztV6/aYcUaAjs=,tag:6NMOKTGtZbwcUClbrOYVqw==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:Vy0/7v+bOhkJ/hIZsDeMwnenuUJf0FJh5g==,iv:pXbo9rwDmH3poKwKFVQ0V9x0SFgxZqXn06vJVUoz9e0=,tag:suT0LskdhCQuGkagl7c+TA==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:bvRxfsU0DnVu6nse8G/T94eUAqBRbevq/A==,iv:50CJdsUjp/4uEa1YSH9QJ8X3hmQiYOqnxby84pkY7KU=,tag:3Q0u2cCuH6gtIaDU4k7fXw==,type:str]
    NEXT_PUBLIC_API_URL_AUTH: ENC[AES256_GCM,data:yS5tv66BGmwiwSQXyuRq3rxQY8IXkmLrGw==,iv:rsQQk4hELjSinDARX/VHs8/Ku/aWTJAm/ZIrB8lu4QU=,tag:cfGBKK3t0lfElcI0lfY0eQ==,type:str]
    NEXT_PUBLIC_API_URL_DEVIS: ENC[AES256_GCM,data:f+fyKhNfzISpG/Fp5uKLobDFjqeX//epig==,iv:tzoHmWAt/ZN4E/gOWOWqzvGqAX5jAvQRAxmk67GX5XU=,tag:W4Hyngsu8eHse3xn09Kryw==,type:str]
    NEXT_PUBLIC_API_URL_JOB: ENC[AES256_GCM,data:yUUQLsXUrdAiUd3YbylI/1IFQkYEKwLUrw==,iv:29TG9gxHlIdzxk692xzV7iCFMbvoyjpoyHV6Q2h4KDI=,tag:+Yru8Iqo/hJGiupsHhbhSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaUxjR1FheHJHeHNsWVZr
            UHhoaGlYWHJ0WkdHS2pURlVieGd6bFBFY1VVCjMycStCdVR2NVYxcGpLUXJRSS93
            aGt0QWMvYzBWMnZRQ0d0RlB3cGV0UVEKLS0tIGlzdkRrK05aalVNMElLdE5OM2Ri
            NjZlVXo0b0pieHBQRzRSVW05cVV2Qm8KqrrE1/Tpr6gIQXs9N7cd9N/8kZCqOHXV
            dj8WMHkir1MWI3XkLJ1Q7ttZD1NQX696bjBxmiyE0pDIJ9Pm0LaZVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:42Z"
    mac: ENC[AES256_GCM,data:aB8pdm6eHEBQDxIpFnG48KgBQC5yXc5b7798gU67PydML9FNGYFcLYyorckIYtODKL49tW7lauc6b74Ox7NPgjSzv8CkzDsdNjdO8DSatNXKyFmxT5KZm5ldaKcubJgPQznP6CYaO60UFbhIPK9V6dojYzsKnxtke7nYL/baqpM=,iv:3heTtGTwLgu5uE1hXTmoM9YAuLX5vplHbiXryxqTwgM=,tag:EjdjQP9unnsr9odSmE8kfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
