apiVersion: ENC[AES256_GCM,data:f+s=,iv:hMqrosw/nICjbncDx/Pz7cH1bDRSekD8Qhp87P9TOEE=,tag:Ks5AhViPiEN3s5IOSjXOVQ==,type:str]
kind: ENC[AES256_GCM,data:lufkOEap,iv:cMupCxJV3G+2d7VlnhZWePmBUrUwMw16cWMgRHCI/ho=,tag:R30WqulKV4oNCjYC4EmVpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zNJy2PMsp0eGOJYrXmgh5W6euhPduKE=,iv:nF1RNTVPG2H4gkvfiJb5MYQOsjbeOean8YuWHAVfbfk=,tag:EOT3tF3gFOW3Opt4JBg4Dw==,type:str]
    namespace: ENC[AES256_GCM,data:acnZ,iv:ZZYOEbVCEW975g5HHpKAz/xPtTKhPeE91zJuXuTq368=,tag:l2c+rp4fkXkbVsY5JfQWTQ==,type:str]
type: ENC[AES256_GCM,data:nJKB5AiP,iv:R6nXA4A9A+cuRB/0oeX8I2zYAnK6eMpjlk9CsDJxh7Y=,tag:/prSZItJn8N2FpJi8xtT8Q==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:ZtMoOPIOBUoYAHL4GtFfbdNi7g24vuQ+LsMl4Nfg83kEMk/QMmabZLIjVaQILGmn7InglFfloOyUP+g1acbbDPI2i7NQMBKpOfNo3JfYVLSfFXweym/PFYJASVBQbudHY8oTqjDkrPHaoxrm4Bxa//FOdYf9igZeeQ==,iv:ZJEWMphVF2X3DKVcOzmyHzr+mzsrGGgQoCZWRkaaUaQ=,tag:vzqRm5jFkLzU0+75iaRT6Q==,type:str]
    PORT: ENC[AES256_GCM,data:6XWalA==,iv:JT0na8W7IN92y1+gcEvjlRQuYO+Ubuy6XYchtoLlIFQ=,tag:hqtd+9kE9trugLg4mcNOOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MnlUNmE2bXJyRWRnaGhq
            NjE0d0EwQjdHbDRuU1NvVDBqSFpEWW5iUlVrCk5aU1JzUmRTN21OYTFLVFdwV2NV
            c3V2UkVMMUVsWkVaaWljT0szVklPZ2cKLS0tIHlkYmpJdHpFNTlBalZhU1NaVENE
            TTJNYTJWb3dWVlhtUit4MlpGbk55amMKlAsJ5gsgaU0GT5JHHaDZu5Hdfpp/3xfy
            eXvDoaHsbdeeWbgpAoy13xcfBQpnwKNUiYHSW03VxYvVqTgYpg4nHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:49Z"
    mac: ENC[AES256_GCM,data:QpaAXArAaFavpxy0XZrq/02ws0I7orV46+aTBuM/AgTHbnxPje8sPcP9RybRPSVa9Rb2v9RRSYcQAojzFHZQb+Vz94sDqD5GT+AiMfgPQBu0ReMIYlTPX1dKsuUQRghfcHjLUuLoMCNwjzaBi8QgWR5wJK0y2Fd0wMv8x9SIUb8=,iv:IU0taZ4FlOqP/g/LJi18NCTsqmCqsIlUe1GPMg7DgpU=,tag:dNvb9s7bNd21gfEw4Cu49g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
