apiVersion: ENC[AES256_GCM,data:DAk=,iv:0VGeoIH4AmOsRa94z2sI7dkCTLgYC5RFl3OFaNNmW0A=,tag:OnzDcUXzINXNSMizejSPWg==,type:str]
kind: ENC[AES256_GCM,data:HCyH9oHx,iv:mJ9jnrPsdN/EaKRWW5elhxbi/yvMIx8FeZu5+5Oq5EQ=,tag:VAS0aR/yfYbH9e1Ev1LMHw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/Y+eKmUuZ9P1GJLW12kF5BBAs9lO/pw=,iv:KwTvA4BR6nI8dzTmE6kMXAG8Iy4CxySRxgsjPPe0/s4=,tag:5YRAwdhG3TALF3IKrT/RcQ==,type:str]
    namespace: ENC[AES256_GCM,data:Ge36,iv:m0ebXG7xmNL8dORlMT+DvbMX4GuQwV3KQOEqqHN1Zpg=,tag:O4wGZ+avSVexBOTXJ+w/PA==,type:str]
type: ENC[AES256_GCM,data:Q/e/3le6,iv:vUqdfocijIw/r1v+lGePYsdmGw3Pp2h/YLwN+IR2cts=,tag:OFtt74VFh9G2WT71crtLUg==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:MQvK4JxJYhsG0712xW0r/DBVvkKTY0aGiMih7+Ok7aKy8uZx6Odgq6gt+y6zWusl0PhEHN48iIWSU0Val9gJesctIC9h1HOQM45AYUdndYw8SoQRRhkIHA7j6GJqtMT2GKqmb0MOmxF/6i48pQc/SrmJGagRtzjaUA==,iv:pKdYDhA9LRoXTi9ikA0KyIMKOw6zVzWSvMxxusSvHGo=,tag:RZHmkEZ/j6XtKYCkgqHqGg==,type:str]
    PORT: ENC[AES256_GCM,data:b0nNOQ==,iv:3Fj/0dsxri+G+mQID/PvIlsnABQYlVnj4j7Rnqlmw0M=,tag:iI2PWTu97fxB3E1o1Tyn9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxajFJVDJNRC9FOHRNUUJT
            T2Ewdnkza2dueGVaenZ0bnhXWm1WeWNqQUN3CkcrVGl6cmo2Sm4yOGxnOEdyS3FI
            NEVMajRvVjVaVTdrVnJYbWpEL29FZGcKLS0tIFZNQXhhMXBjbjhXbklJZVIwVStY
            QXQxVFNxeFNOU2c5MGFGR2EyZW81elkKqNWmRyu9AnCwn6BWN/Gl+ywo+RpEBaGE
            NltbhmdmqC3q6Pzd4gt7O8UlR9/0Gb4IXJEYIO4TO2ENBS3DOaekag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:48Z"
    mac: ENC[AES256_GCM,data:dC+53zN1XbrXf8iAZYPtB2Tq325fNHF8shfMp6uyaxpHGRzMRmSVk96KiFBw8Bw2SXlVJwD6vXqHbJoavkbBmd1UKK3KQanXL/x9MZvXEjtOmNgbiYSd8HBmAKLhKLEhiQHBGtaT9bxBX6iX7p2sQ5i357uEbyL1wEkQJ8AgyPM=,iv:D1qp0NOkpmnFHSw8kUHQA2fQboeZlXqk5FwtuzU8FYY=,tag:fH5fEgggOjU2qa0A2BhrNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
