apiVersion: ENC[AES256_GCM,data:P5Q=,iv:DZCNaT/kjy8u0G6XUyloLix5DAp8Nxd1Xz2HtQSATT8=,tag:ZHWtcJWah33Bcc5ul6l9gA==,type:str]
kind: ENC[AES256_GCM,data:cK723yCl,iv:4qIIt5OHlXTO/CRXsTLJq67nijqx0kz9ID+v98ppgq0=,tag:ozSUkgAVMSziLy9WLYdCsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:teEWN6UTHmOO0Lw6Writzf9AShnBJoc=,iv:fpFYqg8Dp5n35bOq9nveQ9pzlxFlymlE8MUeTA0orVY=,tag:3ab4gfGlB2c5IqgO0rMXbg==,type:str]
    namespace: ENC[AES256_GCM,data:m4hy,iv:VPFFuC/qqTIoBcbvqxqUeO0YbyzjsvAGLV686mK0UOw=,tag:Z08eX6/tB96pKWQvmU44+A==,type:str]
type: ENC[AES256_GCM,data:QRanQjwR,iv:8ZBgr3vPnjOWg5FQdn9sT+GNN5Xf3SrkgP333REcF5c=,tag:Iz9wA7uCw/vdUdBIj5wvsw==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:zzAE3UMWGMXlXBegQHUofq3w33wyG6k660ZZczKyFxXe9gVwsyFyVxvTGKaLmkH3zkavN6yDAjAPtcnpqowrO/BUA6okZqDKFYrRLO9X5RdODpVv1c4OhqYGsrnbny3VHXsZRk+k3aAEJynsMFQ2NT+9I71Gd4Dibg==,iv:FbVpqo4u6wCCFBeWclI1yDIdTbWH3xtcZGIlfvZDi+4=,tag:OSlzCT12/vl148DRhN3tCQ==,type:str]
    PORT: ENC[AES256_GCM,data:buA5EQ==,iv:+ifXpcZLAvOAfOTNmNLwmipp3n6+KGXBRCvvzNwj8nk=,tag:wPDkfTEV9MQvOPlKGGHgdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV1YwbDZPd09LdDMwSTY0
            Q0F1WlVDMElmVG9SeDFDZkxzVk1ENHU0MGljCnVjQ2JXR3AybDh1T2M1enRYS3VU
            QlVXUy85Q2VNY00yUGRYUzc4ZllaRkkKLS0tIHI5VVRRWTBMOGxUdi90MUx1TGg3
            cUlXQ21uZjFFK3B4YnYzUzFQUFlsUDgKrGB/XBYLKio4pUk4ixKFeHRy8SnyKxFu
            yKWewGFspU8Z0JKaqIukza3C2B4uh8gAEUP5PnI7mIWXobUW29larA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:04Z"
    mac: ENC[AES256_GCM,data:eve2g2v/omrmeLr4jn+/oy43AF/Gmhw9XKnH7LfG2FgRK+nlIWNenzsYZhoCRXPsUYh9r4kXhAbHiAUpQAf1DJdPPlynyzxnH8H/Qv3U4BhAWEX9BCjxq/lej58DEgtRku6TyGgXiJAl3cgyLoOKDqdleeLBzWrN6hqwUs08PaQ=,iv:+ZG6LifnoBns1JWlgmu497HsUxLxDI8M9aHLKQY+4Vk=,tag:b1uRH7V61yGF0n2RkN4s4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
