apiVersion: ENC[AES256_GCM,data:QZY=,iv:+4ngdn1IGiFD6H+UvqYMjHjuWRq4uLAJVhZnCSj4tC8=,tag:YzGx7YaY5slVQX3Oh53+9w==,type:str]
kind: ENC[AES256_GCM,data:2Cu+tHYk,iv:/QwdrWezte1I+HOB0VLRQBB+gM4Euvfk7+/hhiD/NYo=,tag:vez9yqoovFwx1IOT2ydv6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rJWOnZWbS4pfR0E3QgfRYw==,iv:NrPfqkBl9/J0rFFxyqdTFpMZIzdj0QWmtsgKNbW334A=,tag:3zYEMCpI6X0FampY6zPyuw==,type:str]
    namespace: ENC[AES256_GCM,data:GusW,iv:PVwxT8oBtl3W7VVqKg9w5ve3T/bVPVtHJs8BXuXaLbU=,tag:2MkpGJMDEJ8LDTxiQJc58Q==,type:str]
type: ENC[AES256_GCM,data:m0CnrqCg,iv:2HPq052SUTvLTHlREvqkpeuQbSPdNDNnOqGF6vC6lAg=,tag:5mWsyGniJA+UCojDsZQzsA==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:LOygDd8BEYKt2REZBsbDDpJE8NOHuWzhow==,iv:kTeb/l8++pfTTBIowoEvD0VymYzU1HQXfhh/BIFzoRA=,tag:P98YQ3zKjJ9xqe2sh0noPw==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:IDTNBSDtcpfc2zu/VCp9Jn4wbKyxlongWQ==,iv:tmJw8N5+HFfM4Z73LKiIyT33WhvTaOI883MTfWwQjzo=,tag:0X5AcELu/TozSaISBNV8xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMldHdWNuRTNSR3Z6aXpR
            ckI2SjkrNUhlRnVIdVFSMzNJR1ZreEFDVW5RCkNjWElpckhTR1l2eW1RYzc5U05K
            TVZaSW1waC9OQ0Z2ZnozdE5LOTFnMTAKLS0tIE5jQVZyVCsrSmluZFZNVUM3dE5D
            YU4wbDRXNFdQUE1NNHdDZWNVSlkzOWcKm5dO/TU1zIyudpmTHx5O0yCvhB7ZX8+a
            7aZOQ1HyNVBpnXRH2oDbanT+gojLsSIUL2hSulTxhReYhAF6sOAnOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T18:24:45Z"
    mac: ENC[AES256_GCM,data:605Xv53iuQcI1n/v47XG57EZZLItH+p//4ZHnLUmKsMldJT0D0NVCDjCyZtfbqL1/PO0fHsrcy4TYCbO3lcVwHMR3UR0k69tJB++g8H9QXEBt06jxzoVrZ9rtVzFcJ7RoU1ZV7y6iFx02WAK52hS+yf500gWu9O6fPdB+mBxGD4=,iv:WNTJWrvrIVUPWdyb22hahmFjsXUPZ4vDmvmAAEhrAKc=,tag:zgu10rg8HuyU5K4UV7sNjg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
