apiVersion: ENC[AES256_GCM,data:eQQ=,iv:o5xfaqNYe3nN6zWJZ2zCsBWHUt/2Gb2p+LZC6JqP4uo=,tag:qVd18kzp2MpQe5EaZicaQA==,type:str]
kind: ENC[AES256_GCM,data:3erI9q0K,iv:Jya2bNjfILcVI4GLJkj8M3Yml3sIdQCDMFS4lyJ8uUc=,tag:CeI12rpwRD1v33QoyAmPTA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z59S9HGutRegjpFk8omVmw==,iv:Ld4xb4bLOhc388pRXbOmUuhP1HecyPoFcgI5yYjB8/Q=,tag:RkFjqCZ7/jQM4JSrI4XVJg==,type:str]
    namespace: ENC[AES256_GCM,data:N8HK,iv:My1NabwlagvGhG5WfoLkQOB+9FSYkHVOKPuFPIUloz0=,tag:lbWbVFM+OP9KHtf+Uc72dQ==,type:str]
type: ENC[AES256_GCM,data:Xkxc8YcC,iv:y0hGtRVCk176wH5Z70CCB2owt+lRc4CFGshNBE3TtSY=,tag:YFbxjGdc5rY8c2W1PQ8k5g==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:ujXTEw23s8nmRj3Va8YDllkue71WpOnjFg==,iv:bCcu5u925QGTot9vaJyAQjynrNPVZdmiAhASk67czEs=,tag:j/gny5FYKF/MDohLlTlBTg==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:Zk6ChRA2cufyQ64JEiQw5VIG4U4faaCekw==,iv:A8V+SSxl6pIjcVhHMoYvhYqxfbtpZTqniywx+JzJPsI=,tag:+Z5PHf/Icmp2pw+ZAt1suA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSHI1LzFTZVlvaHBiZDJi
            M05iTXcva3Frb1plcnhGSjkxQVVUR0J3a3hzCk8wUUZzTlFLU2VYdzc5TFBQaFlQ
            eGU1WXAzdEF3UnR0SDBCUHFPeENEWFUKLS0tIGtMV0VvQjg3N1FsY1JUN1JSdjAr
            YTM3NUlTei90T0ltblNHT0RuVlpHbDQKnqYG8v2jVsjYszwiOc871WZHAeb1NRib
            BJSt97dTglDUc2KRdOmwGblXfN6a0vV+euhl51VK2nAj+xxc/DN4KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:04Z"
    mac: ENC[AES256_GCM,data:ZRg1Q4QNmHjWokD0Hgcqmi5oIUiqOnaZyyNWncNhodJjan+JKOtWbQVpCf7Z81YdrL6qjSRYrTyrA/pZa2VjQ5WpUk+9P4QJjaGA7JhVHAH49FsHsOubQ5hqiqPpVzX8IqPD9YxDZVjFCZbAM+PCZtCu5sEz0a+x90CYJPxgZRs=,iv:liD1D87DYZ++PvptXngdoUMffWIsybQBuaXb6aalJ1Y=,tag:tdpLkNPkeaudPOjnedcbxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
