apiVersion: ENC[AES256_GCM,data:AvM=,iv:lvEUGmVr+lFR7Edfqv64jiqMN2dRhfgJe3jzT5OEXhg=,tag:t6Ic4QaldU6eaJcLp9ZPXQ==,type:str]
kind: ENC[AES256_GCM,data:SBjFqN82,iv:+DkCDfOLoXnTdf4/s/Ge43o1gwsllB5kaPwDYwOAEFE=,tag:sUZPciNV8iE2jHzD7f66pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s+sEpeYSK4gRcgem4bQCPQ==,iv:2GqIxxdRJ2B1/K6xpjLyjSmVyMTtH56GrSZG35eBQfU=,tag:gsRlVT9yKbKEME0lQ9B0zQ==,type:str]
    namespace: ENC[AES256_GCM,data:ll3o,iv:z+KhW43c5aqWrpjdIa9cjb6m1pb55LDwrzQucdASlvk=,tag:o5dSzr7wMkTwpOd055KUBg==,type:str]
type: ENC[AES256_GCM,data:B21coPD/,iv:/lK6SqCcBlI41qvAky99aHq+m9yH64jSbhb7rfEQ/vs=,tag:TQo9lhDZtEAlmKG0nEogfQ==,type:str]
stringData:
    NEXT_PUBLIC_STATIQUE_URL: ENC[AES256_GCM,data:HuVTqtb/YlIPB/FTyDYBbMdAWW47ibgwNg==,iv:olknId+IadI+VaLSmb8Ej//mfzgeG0caGVEALVvueaw=,tag:Jc0sePpyZQAgryraVBxfjg==,type:str]
    NEXT_PUBLIC_DYNAMIQUE_URL: ENC[AES256_GCM,data:J7M9lSfamyeeXr4XkGUHLatzIEDZODu5+w==,iv:AUk0ilnSqsqg8D8PZMTuW5D2bhDTiF9jl5iyJqBpyps=,tag:LowMk5TbpgWYUWYUtA18TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWmJpVHR3aU9PZjFWK3pn
            blhJMFdwdzRJeUZXZmVOa3RwYkEzcnBOOUg4CjdWK0l3WjdjbnRwNDA1d3JDTFMr
            Slc5Y1B1aW4vRlY4akJUcU4zQTI3MFUKLS0tIDgzMWpiRU0rVEZPTjB0N1N3NC9O
            RTBUTk1LVmE2ZlpQVHdBdWxtRTNsSHcKfht4Zd90jMLQJ2gGsuS7d+htGko/CveR
            v7KOdK/6sV/7RbRZVbn9gv+ruqSpcs99PJYXqJ8FLLYzSYxuC4R6Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T19:26:50Z"
    mac: ENC[AES256_GCM,data:3H7JN2Bfn6f9f3VsnkHEJLm5qVakeL+xD2UZLh7JxGggfuv+a3ImovMyG5lC49ikJ8mJtWY2xTVERks3o1YBbSpVLCETCaCSIW7bZjBAoe0joV/43diMyfhlKambhSnWpD0r6UHRf7B1YmXnFzim7V2Cp9rQ02zxhQ4oiVWWc1I=,iv:2Q76wkCnM6BxpVBkeGe0dWK0yXojwFWKO0ngw4aDERc=,tag:Kx7G4Ihj0mQMEoMTQVKTMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
