apiVersion: ENC[AES256_GCM,data:Ims=,iv:aUYdpzycFcX/p6qKT9yszp/pzXl/ZrDaBYzut99tWKU=,tag:3eGhlgBV5UfwxUUZ24RiAw==,type:str]
kind: ENC[AES256_GCM,data:sgqMZk3Z,iv:ETR3RX5DWxTBBSEznL2rUazLnKMC1ZoCxKmuK1VEsxA=,tag:FnZSXJNOd8Fwo0lRhv8Zbg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0J6w2Q==,iv:2ivghTI8+ZsqJnYrr9oZMPQgqRQEJCPEMYCUzalu7/s=,tag:fZ2Vo80i7CZqmuvDD2glWw==,type:str]
    namespace: ENC[AES256_GCM,data:CRu1,iv:0O4AVoAIAT0GAw2LfoSb7XfQuPIITDCr+B2BIGRLhLU=,tag:zPAvT+Aec6nNiH3gpsKkFA==,type:str]
type: ENC[AES256_GCM,data:xJmmB8OM,iv:eAr4uTsR4FXRtdm9SxLRIdZ+4zJ53gkI9teG8XGqadI=,tag:rTeyD3F9MAqv1sGsmiRC3g==,type:str]
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:R+7Jww==,iv:qnVvLez+A52SvdtyLlyYmcqZ8V28NBvsFJ3PQ8W5orc=,tag:Dvz3mB6CkSYaY9LRpv2KMg==,type:str]
    PORT: ENC[AES256_GCM,data:qMr6tQ==,iv:U+skhScetqxdgGhjUj1MAtfmMh6KMAZROt7BHIqxrYw=,tag:mwHLURESeo88h76YJl03mA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:iaULKPYI7bcyhb4KxSo=,iv:LvH3ztSj0iCYzdmztR4yF0wkIl9g3zbYHC1uWXOPpBs=,tag:UnP0IysJwnLFCcyWB9GzQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVzdodkpLL29PMjJHUEp3
            S0ROcTZ4VHRMVFhwdlZXL251MSs5MDlNS1drClR3WXFXZ1lPQ0NYQkVyYXR4MGVC
            MWhFekZrYTZDc1hvWWFQQzhrOThTYWsKLS0tIHJVSkdKdW5YaFB2clp5c0ZQOUQ4
            UmwyU3VLMHNxVFpZRWRZVWMxOUgwRmcK3zcyp43MwGMxGob/rtcxv5slTZC2dhyK
            L1Ra//xowJP93yJQ+Mkk/lfmRw/9NHbFgrbNaYrt1iJ55YUfLq+nxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T16:39:48Z"
    mac: ENC[AES256_GCM,data:okzlXKmP2gNe2JNpetwgtgtoCT1BvByBLvoDLJi5ohWA3u6GQgXBsHnhH8muAQ+jFap2buYNrtyvNpaurCguTGGN4ATeApYy7UtkjAVMWlmf+do99FNk5iS25xf+aoKcJgWRT+Mm7BFWAVoftzEv3sbMTj/sSxfiGV4SoxjYt/s=,iv:QfyP/KXMcOWoY6KgZIQ8BrmjzuQs64PqMuPGc3ufHiQ=,tag:ajgFRWjtFZENgFQAq6qL/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
