apiVersion: ENC[AES256_GCM,data:UvQ=,iv:gN+QYMsRzO2Zlq+E3A+HBiBYbDweYgn5SdJDgRrzxvM=,tag:GWQ6nBMbSatYQ0UBPExrMg==,type:str]
kind: ENC[AES256_GCM,data:XB7Hherk,iv:j8WzX0K4WIGBAEkLZtcPSrA6H1+9PzRZJaUX2K1YE9k=,tag:opo8xDUITQAiW80HebMvZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Dz//Tetg/qDuJqDHWPA=,iv:XU7bgRBDZDJklm4I2d2V92bWUUa8/x1QhOf49CQi54w=,tag:Ca7kM9c4L6uNWIXIsWLerw==,type:str]
    namespace: ENC[AES256_GCM,data:4vBp,iv:kzHO7vWm4H9ASKCJhrE52MIufIt5D4ols4r9GLOvkM4=,tag:T1OzBPM6S8ejH/BbZfqqGQ==,type:str]
type: ENC[AES256_GCM,data:X2yzcPqG,iv:yh1x2gxW7otNjyWdSZTrMS365074PG0u4koVZj8guIQ=,tag:GkHQ5heQcjA9OgnEDkBMdA==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:MHVppw==,iv:sk2PdwOYPHZ4jmdOxNzrROePgfR2FjoZRlnZaxM51mQ=,tag:Knfg7cUw5jBZToJDa45i5Q==,type:str]
    FOLDER: ENC[AES256_GCM,data:4Ai5fgdYvQ==,iv:WLsHu23eEmrw0BrR/2PZJPfqdiuVLfptQDNmS0BGA8I=,tag:0//lMojXLoGIId8MVp7jEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMHdQajltVFJzZStCcCtI
            NzFwUWlRZDlmOTNHZUhZY1kwdkMyUVJCMHhVCjFMb05QU2hEbExvNGJacVFxRmhN
            OFlaVlh5bG9YZXBoUVRYOFFmdXhiaEUKLS0tIHhwa0VOTWNCbndUQlNscTQrTkRM
            QStVdUFJZUNrOEJHUGlsWlBGOVNIWjAKkt9PVl5fKk0BaWDjfzjsPDyeMMesNtdi
            sJnYhdBf9UXk9UbZVfnYf9XBpHxL3J0QIKICgu+DxQmC/RXlZ2iANQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T21:41:05Z"
    mac: ENC[AES256_GCM,data:0NZBs50hL0gORq9JVxNqCTArOix/mDPbon2E+3sayuQ0mkM87J6VQoo6mpEwvc0dxBofypvtb/pK1hz8uL+nCojvkduzCggnWGqpRh2rPrM36yoZhzw0nkKQJMqISUhi+RB1LXt0Uy7YItruNFEAWzfgt3crEyuUHK0ebd2L1SY=,iv:jZFctMMo91eO9jdD5Jah5ocJUr6Xjc3RfTUxeH9jS7c=,tag:IDnh+iJVuZLUmfZABSk90g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
