apiVersion: ENC[AES256_GCM,data:1ME=,iv:72l/uuwycAc8bRq2AHBgwhEBH7M7pJ2iRt7ZEjVVy3g=,tag:TWIBpq1aVCKtdM6BXVEJJg==,type:str]
kind: ENC[AES256_GCM,data:xLxv7i6d,iv:HHyYxX0gIgNYx5d2aKzzPY4KuEJA/MZiCfPjLWvQFbQ=,tag:1D93Ct2mYqxPSmQF1ZjsFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kLFdWGIQDr70g94q2Uo=,iv:jzGZxPzhR1pKDuUICIyPjRgiRSersragjdFDlt3fQqI=,tag:9m050pV8AJXJ2XYF5gP3vQ==,type:str]
    namespace: ENC[AES256_GCM,data:Cu8r,iv:arCjI1Doqk46unG8oB5yjRQh4sggfmzoLYdWfqClzYM=,tag:pAoDfvLGAeQvuBb4dXhG1g==,type:str]
type: ENC[AES256_GCM,data:LwH9gQ6t,iv:VfR41qiIG/WDMQja5nuj3MtBDkSUW/X7DE2qB0CSgKI=,tag:gSyXo/GGe+0ywcTE15h88Q==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:/y8lJg==,iv:tpsHtBYyNU8uQHAXcVRb5//M0/iMThdGqilp7jAu0fE=,tag:u9JhS/p6cmRkkd+ye3FV5w==,type:str]
    FOLDER: ENC[AES256_GCM,data:C4zMvZF0WQ==,iv:tz+wVs+2rk5+DJs96Id/Yp+alWyqZ0kt23crBLQm4w8=,tag:ULwpR5sg7l3iHm2sGH1ttQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTkVMUmQ5eHBjSjhJYWF2
            VHZoQXNoMTlsbWRMSmtpUHlEKysxbmRiZXdFCjdoa3dlRTU1NHRhczFGNVVYSHRO
            YWd1Ti8xTGNYL3crWGFoRVUwSCtKSjgKLS0tIFpwSTNFK3N0b2pHTDRlaXFiVzNr
            Yi8xWmRUVHdsVENsSzFtKzUyR0F4VDQKDNR49z9NhJh5f29WD2/OmQhlQ9JSzSg3
            +cPBhyXwNnqodx6XBgK5/N4VoNuM9kn3pccYMMPH7O0ljZE/RqbGXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T19:40:49Z"
    mac: ENC[AES256_GCM,data:QALrOMlI09nIE0r6AhuUuHKUPrhmgNVywYgo3q2GiXFA4zex9ktAAWp35ktkOOjJ3GIJkhlO5lowml0+T1h1B1TTtYKYgF2L1YZVfV2rQ76oRCTJwZNkmNnYtYJAuNhi1kO/s59fesKeVnPGegBAHIRHyjM165GYy5qBeh0AKRI=,iv:4FMbjEHNOp+GBXPOqv9L3hQWXFxiVWYAoUBXKxF5dOs=,tag:BpE0KPFFrST7ijv6Weg1FQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
