apiVersion: ENC[AES256_GCM,data:2/E=,iv:vSoQYM0FdPD+qWA1IELUFgIFq7nqsIlHOlLYbCRLZ28=,tag:witSG7E2VZ2O2UTyK99grg==,type:str]
kind: ENC[AES256_GCM,data:BXGvseJ1,iv:Jwpvp6lVdahFYoFAVA1XFOWQUDhtKO61eFkrMiJhTC4=,tag:hikLsR2C+WPV+UdWlavboQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tdBpAL2OJSQ5Abgm1lk=,iv:TdFF6UWDJ4OTE/CBmTV7f1wnoCwAffocSY7YPte5al0=,tag:X7DtqPUFPzbaElUvCX7BNg==,type:str]
    namespace: ENC[AES256_GCM,data:Ms2s,iv:KIdS4K67b4c9VacYO83TGfJoLXIJkU+N7G95JWHAMgg=,tag:RQWdMUoeseAey7oQV3phyw==,type:str]
type: ENC[AES256_GCM,data:Nvd7tLi4,iv:aum0fOWpVDDuZsTxI41Lx5mQZXUugtW57slUXWA0n4c=,tag:skR+5CgVGD72NVCpi/BwfQ==,type:str]
stringData:
    PORT: ENC[AES256_GCM,data:Yzhj6w==,iv:I+somkNtShgvR3dIeRywDpQanmF3bGjXG30w+nfsymI=,tag:VBhznrFBAuFhNzG/a+iDSA==,type:str]
    FOLDER: ENC[AES256_GCM,data:ezy5Nf6tlA==,iv:VxdFGzxNAEx8Hz1Ewaxz4mb1jgdXMrQxxziY0Dk1258=,tag:9YSHf67/PdgcWRS1PelV/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d8gu2mhr02czhhkwxtsdxd9vqyr6psl7smmg8ckf97v2d98papvsr0xgar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS24vdEtUeFFZa2VDckQz
            ZjhOZ3pxazZUaVd5WTNyOS8xMWN6OVYyOFZZCjZqRU5aKzhKUjkrR2l1NnYxK0x6
            MjZyemNhWENRLzZOOURJTThRUjFEQkkKLS0tIFdDUEZ1TXdhUHhSa0FNREpZQWJI
            N3ZRYko0K3lCanhVMllEZ0MxMHNaeFUKkVXS6ziHcpXxVAEgh9ZPzWB1PC/2Kr2p
            n6K33TCLVXuNXfmZHkPWffcMjQcfzy9R62C0HkCeP4/ToqwAVxstCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T17:59:15Z"
    mac: ENC[AES256_GCM,data:uG13glQnvr7EgkkZSTrnip5/JoPtacUzfkNhxdnLQ75jym5Le+xwblbMl12N9C56WKj7wa9+WDI4dBK7SJGFyX25ZEdhZ1/hXWmb38qilUClFuElVJ8qW/YL3W+YEbWUMf4xWsZRlfdj3sK+f7+x+v65qIuv4IUd+iFRLPk2IWk=,iv:cuUUfjVn64VHUeVYdaMX/TaKzcy+HM+WVpCrbbBMIGQ=,tag:/LXBZgA9QS7HJK0IKtsuIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
